### ISSUE TITLE
Automate adding function name and test number to the test title

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#1]
A function should be implemented which adds the function name and a test number to the title of the tests. Additionally it should add a comment before the test such that it is displayed in the TOC in RStudio.
For example
```
test_that("duration and unit variable are added", {
...
}
```
should be transformed to
```
#---- derive_vars_aage, test 1: duration and unit variable are added ----
test_that("derive_vars_aage, test 1: duration and unit variable are added", {
...
}
```
If the function name and test number are already in the title, it should be updated if necessary.

Please note this is quite a large task and good for someone familiar with the RStudio API.

**Comment by slamao** [comment]
HI @bms63 , I understand that I am gonna copy the code for the addin here. It seems though that I don't have permissions to write to this repo, could you please adjust that for me? Thanks

**Comment by bms63** [comment]
@slamao I added you to the repo.  Thanks for following up on this!
