### ISSUE TITLE
General Issue: Increase test coverage for `compat_friendly_type.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#101]
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests for `compat_friendly_type.R`.  

Unsure if this is a good one for us to tackle.  @thomas-neitmann @bundfussr.  I'm still not entirely clear why we import these functions (3.6?) .  But should we build some tests around these gaps?

![image](https://user-images.githubusercontent.com/10111024/191840815-bf0eb76d-924d-49a6-bb3a-db695afc42cf.png)

### Definition of Done

New tests written that covers the red gap area for `compat_friendly_type.R`

Use devtools::test_coverage() to reproduce the report

**Comment by zdz2101** [comment]
Tracking the use-case, the code chunks highlighted above are used to display user-friendly messages in a couple of the assert functions, in particular, `assert_date_var()` and `assert_date_vector()` which are still in use by many admiral `derive_` functions

**Comment by zdz2101** [comment]
![Image](https://user-images.githubusercontent.com/43018762/199825932-df57b1e5-c06e-44a3-8d45-c604fc8b05f3.png)


![Image](https://user-images.githubusercontent.com/43018762/199825991-b3b8dca0-4459-41dd-8d94-3c208c6bcfc9.png)


I got to this point but not sure how to get to the last bit of cases

**Comment by bms63** [comment]
I think that this is amazing progress!! Let's just merge those in and call it a day.
