### ISSUE TITLE
General Issue: Increase test coverage for `datasets.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#104]
### Background Information

@thomas-neitmann We can write tests for these right?

![image](https://user-images.githubusercontent.com/10111024/191842000-35ac2e46-0501-4336-931c-3d2dffaea789.png)

**Comment by bms63** [comment]
Also while you are here... @thomas-neitmann ... Should we write tests for these warnings with the joins? Seems like a nice to have?
![image](https://user-images.githubusercontent.com/10111024/191842283-0a9094bb-d162-4875-bfcd-0d8c8f9b2e35.png)

**Comment by rossfarrugia** [comment]
@bms63 FYI that a new contributor Jen will try and tackle this as she's building up experience with unit testing. I just went through our development process with her, hence the draft commit above and PR.

**Comment by J-Lox** [comment]
Just wanted to feedback on this function. 
The documentation that I found for it is lacking any usage examples and it is not clear to me what this function should be doing. The reference page suggests that a dataframe is read, though when examining the code only two values are accepted and I could not understand the purpose of it or how this fits in to the developer process.  I would suggest that some more detail needs to be made on the documentation side to make this clear to new developers. Thanks!

**Comment by bms63** [comment]
Thanks @J-Lox for the feedback.  

@bundfussr  @manciniedoardo  some of our `admiraldev` function documentation are a little weak and some gaps in testing.  Perhaps something we can fix in this release?

**Comment by bundfussr** [comment]
@J-Lox , you are right, the documentation is not clear and should be improved. I have created a new issue for this: https://github.com/pharmaverse/admiraldev/issues/271

**Comment by J-Lox** [comment]
Thanks @bundfussr
