### ISSUE TITLE
Documentation: assertions link pointing to admiral

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#109]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

This link goes to admiral and should be going to admiraldev

![image](https://user-images.githubusercontent.com/10111024/192824555-e1090b4d-10b9-47ea-9084-d68a82164fba.png)

**Comment by AniaGolab** [comment]
Hi @bms63 I have a follow-up on this issue if that is ok! Do you want to update the assertions.R file to contain more function - is this the goal here? If so, are there any specific functions you wish to introduce there ? Or should I check files looking for them and move them all to assertions.R? 
Thanks!
