### ISSUE TITLE
Documentation:  Update Function naming conventions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#110]
| Function name prefix                         | Description                                                                                         |
|----------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `assert_` / `warn_` / `is_`                  | Functions that check other functions’ inputs                                                        |
| `derive_`                                    | Functions that take a dataset as input and return a new dataset with additional rows and/or columns |
| `derive_var_` (e.g. `derive_var_trtdurd`)    | Functions which add a single variable                                                               |
| `derive_vars_` (e.g. `derive_vars_dt`)       | Functions which add multiple variables                                                              |
| `derive_param_` (e.g. `derive_param_os`)     | Functions which add a single parameter                                                              |
| `compute_` /  `calculate_` / ...             | Functions that take vectors as input and return a vector                                            |
| `create_`  /  `consolidate_`   | Functions that create datasets without keeping the original observations  |
| `_derivation` (suffix)  |  High order functions that takes another function as input |

Will make into separate issue, but wanted to get the conversation going around new function names and trying to name appropriately so increases findability.

_Originally posted by @bms63 in https://github.com/pharmaverse/admiral/issues/1477#issuecomment-1262253419_

**Comment by bundfussr** [comment]
I would remove the `derive_merge_` prefix because we have `derive_vars_merged()` and `derive_var_merge_*()` and not all functions which match to the description have the suffix, e.g., `derive_var_base()`. Otherwise we would need much more explanation to avoid confusion.

**Comment by bms63** [comment]
We have 5 or 6 merge functions.  I think having some discussion on when to use this naming convention could be helpful for develoeprs.  Same goes for the join function that you are working on.  

Anyways, I'm just thinking of findability/searchability for users and helping developers on deciding on function names in both admiral and in the extension packages .  This part is hard!! :(

**Comment by zdz2101** [comment]
![Image](https://user-images.githubusercontent.com/43018762/202544474-ad0478ed-dcd9-4414-aca5-88e6b3d30094.png)

results above are from a string split of all the words/terms we use in our functions and my proposal would be for a few additions: 

| Function name prefix                         | Description                                                                                         |
|----------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `assert_` / `warn_` / `is_`                  | Functions that check other functions’ inputs                                                        |
| `derive_`                                    | Functions that take a dataset as input and return a new dataset with additional rows and/or columns |
| `derive_var_` (e.g. `derive_var_trtdurd`)    | Functions which add a single variable                                                               |
| `derive_vars_` (e.g. `derive_vars_dt`)       | Functions which add multiple variables                                                              |
| `derive_param_` (e.g. `derive_param_os`)     | Functions which add a single parameter                                                              |
| `compute_` /  `calculate_` / ...             | Functions that take vectors as input and return a vector                                            |
| `create_`  /  `consolidate_`                 | Functions that create datasets without keeping the original observations                            |
| `get_`                                       | Usually utility functions that return very specific objects that get passed through other functions |
| `filter_`                                    | Functions that filter observations based on conditions associated with common clinical trial syntax |



| Function name suffix                         | Description                                                                                         |
|----------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `_derivation`                     | High order functions that takes another function as input                                           |
| `_date` / `_time` / `_dt` / `_dtc` / `_dtm`  | Functions associated with dates, times, datetimes, and their character equivalents.                 |
| `_source`                                    | Functions that create source datasets that usually will be passed through other `derive_` functions.|



| Other common function name terms             | Description                                                                                         |
|----------------------------------------------|-----------------------------------------------------------------------------------------------------|
| `_merged_` / `_joined_` / `_extreme_`        | Functions that follow the generic function user-guide.                                              |

**Comment by bundfussr** [comment]
Looks good to me.

Should we be a bit more specific for the `_derivation` suffix? Something like "High order functions that call a user specified derivation"?
