### ISSUE TITLE
General Issue: Link to admiraldev and admiral.test to admiral project board

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#12]
### Background Information

We should be able to link this repo to the admiral board automatically, but I can not figure it out

https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/linking-a-repository-to-a-project-board

### Definition of Done

Successfully link `admiraldev` and `admiral.test` to the `admiral` core board.

**Comment by duniek** [comment]
When creating a new issue I can see admiraldev and ophtha
![image](https://user-images.githubusercontent.com/9405981/183064622-bceea629-c90b-412d-8ab9-e14ef069ac91.png)
