### ISSUE TITLE
General Issue: Adding 'weeks' to valid_time_units()

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiraldev#122]
### Background Information

If assert_that(is_timeunit(in_unit)) in compute_duration() is being replaced with assert_character_scalar(in_unit, values = valid_time_units()), then  should 'weeks' be added to the valid_time_units to avoid the last row below?
![valid_time_units](https://user-images.githubusercontent.com/112789549/195569015-b4418266-3b6c-4882-82e7-8ec2c1c9b71b.png)

### Definition of Done

- Include 'weeks' in valid_time_units

**Comment by bundfussr** [comment]
@sadchla-codes , I think `"weeks"` should not be added to `valid_time_units()` because it is permitted for `out_unit` only but not for `in_unit`. You can replace the line highlighted above with lines 162 and 163 of `derive_vars_duration.R`:
```
  assert_character_scalar(in_unit, values = valid_time_units())
  assert_character_scalar(out_unit, values = c(valid_time_units(), "weeks"))
```

**Comment by sadchla-codes** [comment]
okay, that make sense, thank you @bundfussr !

**Comment by bms63** [comment]
Hey @sadchla-codes we don't close issues until releases.  This is so people don't remake the issue as 3 months is a long time :)

**Comment by bundfussr** [comment]
@bms63 , I think in this case closing it is ok as no code changes were made.

**Comment by bms63** [comment]
oh lol sorry i thought this was with a PR
