### ISSUE TITLE
Feature Request:  Create an assert_date_vector function to replace assert_that(is_date()) 

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiraldev#129]
### Feature Idea

is_date() functions will soon be deprecated, and since we are removing the {assertthat} dependencies, a new {admiraldev}, function,  assert_date_vector() would replace the highlighted script. Current assert_date_* function requires an input dataset name, assert_date_vector should not require dataset name
![assert_that](https://user-images.githubusercontent.com/112789549/196224191-d3b2944e-e790-46a6-85a2-57a35f67abb5.png)

### Relevant Input

function call should be 
assert_date_vector(date_var)

### Relevant Output

if return is TRUE then return nothing, if FALSE then return Error message: date_var must be a date vector.

**Comment by bms63** [comment]
Is the `is_date` function in the `assert_that` package?
