### ISSUE TITLE
Documentation:  Explain subject_keys option in programming strategy

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiraldev#133]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

In admiraldev programming strategy vignette add a sentence to cover the decisions from https://github.com/pharmaverse/admiral/issues/1338 so that anyone creating a new function knows to follow this convention.

**Comment by zdz2101** [comment]
Do you have a recommendation where this snippet should be placed? Perhaps under [Input, Output, and Side-effects](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#input-output-and-side-effects)?

**Comment by rossfarrugia** [comment]
@bundfussr any suggestions?? i'm personally ok with using the Input, Output, and Side-effects section.

i like your suggested wordings and extra detail @zdz2101 and this will act as a good reminder if ever we do need to come back and extend this later.

i'd also suggest we add `subject_keys` to the table at https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#list-of-common-parameters reminding developers of this default value here - for me that's the most important reminder as i bet many new functions will get developed and people will forget to use this default (although hopefully if they just copy another function as a starting point they won't anyway).

**Comment by bundfussr** [comment]
@zdz2101 , @rossfarrugia , I would
- add `subject_keys` to the table as Ross suggested,
- update the last item in "Input, Output, and Side-effects" as Zelos suggested ("In general, the function must not have any side-effects ..."),
- move the other two items to a separate top level section ("admiral Options").
