### ISSUE TITLE
Function for Treatment Emergent Flag 

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiraldev#142]
### Feature Idea

Create Treatment Emergent Flag function based on below papers:
https://www.pharmasug.org/proceedings/2015/PO/PharmaSUG-2015-PO01.pdf
https://www.pharmasug.org/proceedings/2017/IB/PharmaSUG-2017-IB03.pdf
https://www.lexjansen.com/phuse/2017/dh/DH10.pdf

**Comment by thomas-neitmann** [comment]
Thanks for opening this issue @kaz462! In general {admiraldev} is not the right place for implementing new derivations but {admiral}. That being said we have recently implemented a function for deriving treatment emergent flags. Please take a look [here](https://github.com/pharmaverse/admiral/pull/1445). If you feel like the current implementation does not fit your needs then please go ahead and open a new issue on {admiral}. Thank you!
