### ISSUE TITLE
Documentation:  Remove mentions of {assertthat} in pkgdown website

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiraldev#147]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

Related to admiral [#1392](https://github.com/pharmaverse/admiral/issues/1392) , as removal of dependency of {assertthat} occurs make sure corresponding mentions of it in documents and website are removed/modified:
![image](https://user-images.githubusercontent.com/43018762/198132206-b09b3391-e89f-42a0-9994-e3ed03ffdfd4.png)

**Comment by sadchla-codes** [comment]
@zdz2101 good point, as of today admiral doesn't use any `assertthat::assert_that()` but admiradev still have some programs that's using it. so I'm planning on replacing them with the appropriate assert_* function from the `R/assertions.R` file, then update the documentation
