### ISSUE TITLE
Documentation:  Wrong name for test file

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiraldev#155]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

The name for the test program is `test-is.R` but the tests inside that program are related to functions from `is.R` program. Need to appropriately rename the test file.
![wrong_name for programs](https://user-images.githubusercontent.com/112789549/199741685-a0aee1c3-8d2e-42d0-af14-e7a8931a9f14.png)

**Comment by sadchla-codes** [comment]
It does look like the functions for `convert_dtm_to_dtc` in stored in the `R/dev-utilities.R`. So I can move the `negate_vars` test to  `test-dev_utils`  and since `test-dev_utils` already has test for the `convert_dtm_to_dtc` I get rid of the `test-is.R` file and not move the additional `convert_dtm_to_dtc` test from `test-is.R`, does that sound good?

**Comment by bms63** [comment]
Yes that makes sense.  Thank you for being so thorough!
