### ISSUE TITLE
Bug: assert_character_scalar() does not give expected message when case_sensitive = FALSE

### ISSUE THREAD

**Issue by fshanlee** [pharmaverse/admiraldev#156]
### What happened?

Hi @thomas-neitmann and @bms63 , I created a workaround for this issue in my local area, and now I cannot reproduce the issue, even when I restart R and clear my global environment. However, I'm sure I didn't imagine it, so here is the issue and my suggested solution:

For `assert_character_scalar()`, when I assigned `case_sensitive = FALSE`, if I then specify a value that does not match the list of valid values, then instead of the intended error message, the code seemed to fall over where arg_name() was called at line 167. I think this is something to do with assigning  `arg <- tolower(arg)`, so the value of arg is modified and substitute(arg) does not return the parse tree. I was able to get my code working as follows:

- I made a copy of assert_character_scalar()
- I commented out lines 160 to 162 (line numbers referring to where this function is located in assertions.R)
- I replaced line 164 with the code below.

```
  if (!is.null(values) && (case_sensitive && arg %notin% values ||
                           !case_sensitive && tolower(arg) %notin% values)) {

```
Here is the code that I was running, in which I previously observed the issue (even though I'm no longer able to reproduce the issue):

```
age_unit <- "month"

  age_unit <- assert_character_scalar(
    age_unit,
    values = c(
      "years", "months", "weeks", "days",
      "hours", "minutes", "seconds"
    ),
    case_sensitive = FALSE,
    optional = TRUE
  )

```

**Comment by fshanlee** [comment]
![image](https://user-images.githubusercontent.com/102817476/199962084-e4e174df-9b13-47f0-875e-60767dc01e41.png)

**Comment by fshanlee** [comment]
I was able to reproduce the issue this morning--please see image in the above comment.

**Comment by bundfussr** [comment]
I think this is not a realistic use case. The `arg` argument of `assert_character_scalar()` expects a function argument. I am not sure if it is worth the effort to extend the `assert_` functions such that they check any objects and not only function arguments.

@thomas-neitmann , what do you think?

**Comment by fshanlee** [comment]
> I think this is not a realistic use case. The `arg` argument of `assert_character_scalar()` expects a function argument. I am not sure if it is worth the effort to extend the `assert_` functions such that they check any objects and not only function arguments.
> 
> @thomas-neitmann , what do you think?

For information, this is where I am calling assert_character_scalar():

![image](https://user-images.githubusercontent.com/102817476/199971537-c7ea1462-d272-493f-bf1a-d25c199007cb.png)

**Comment by bundfussr** [comment]
I assume in this case the error does not occur because `age_unit` is a function argument. Or did I miss something?

**Comment by fshanlee** [comment]
The error did occur: `age_unit `is a function argument, but when `case_sensitive = FALSE`, `arg `is reassigned (see lines 160 to 162 in assertions.R) as `arg <- tolower(arg)`, so I think `arg `is then no longer a function argument.

**Comment by bundfussr** [comment]
Ah, I see.

I would suggest to set
```
arg_name <- arg_name(substitute(arg))
```
at the beginning of the function and then replace all occurrences of `arg_name(substitute(arg))` by `arg_name`.
