### ISSUE TITLE
Documentation: Update Programming Strategy about R Versions to harmonize with admiral website

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiraldev#165]
### Please select a category the issue is focused on?
Other

### Let us know where something needs a refresh or put your idea here!
From a related admiral [issue](https://github.com/pharmaverse/admiral/issues/1565) and [comment](https://github.com/pharmaverse/admiral/pull/1567#pullrequestreview-1170976948), harmonize the text in the programming strategy related to R Version checks to match the admiral website FAQ, in a way such that it wouldn't require manual updates for each R Update moving forward

**Comment by bms63** [comment]
We sort got this one figured in another issue/PR right?

**Comment by sadchla-codes** [comment]
Sort of.... I think this might be for a separate location. Since we're losing track, let me look everything and either make the change here and include it as part of another PR or ask you @bms63  to close this issue if it's not needed. does sound good to you @bms63 @zdz2101 ?
