### ISSUE TITLE
Feature Request:  Wrapper around `devtools::load_all()` to check for updates on admiraldev and admiral.test

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#169]
### Feature Idea

Musing if when a developer runs `devtools::load_all()` for `admiral` or extension packages then we have a "masked" wrapper function around `devtools::load_all()`  in `admiraldev` that quickly checks if `admiraldev` and `admiral.test` have recent changes and prompt developer to download the updates.  

Might be a little easier than designing CI workflows?? @bundfussr

**Comment by bms63** [comment]
I think `remotes::install_github` won't fire off unless the hash(?) has changed for repo, i.e. an update has been made.

**Comment by bundfussr** [comment]
@bms63 , having an easy way to update the development environment would be nice.
I am not sure if it is a good idea to integrate it into `devtools::load_all()`. We can not change `devtools::load_all()`. We could add a `load_all()` function to admiraldev. But this would only be used if you call `load_all()` but not if you call `devtools::load_all()` (which is called when using Ctrl-Shift L in RStudio).
During code development `devtools::load_all()` is called quite often. I think we do not need to check for updates every time. I would also like to avoid that `devtools::load_all()` takes more time.
I would prefer a function or addin (or both) in admiraldev which calls `renv::restore()` and updates all upstream dependencies. For installing the upstream dependencies we could use staged.dependencies functions.

**Comment by bms63** [comment]
Agree on not making update to `devtools::load_all()`.

Doesn't the `staged.dependencies` Addin take a long time?  

Perhaps a `admiraldev::update_deps` or something similar that can get placed into an addin for extra flair!  

@zdz2101 Another addin!

**Comment by zdz2101** [comment]
> @zdz2101   I think we should close this issue.  I looked into `.Rprofile` as a way to do this and seems like overkill.  The addin sounds cool, but then we technically have an addin for staged.dependencies, which I have been told doesn't work that well.
> 
> 
> 
> 

Works for me, think at the end of the day, a developer gets "the hang of it" being in the appropriate versions of packages if they're working on simultaneous fixes
