### ISSUE TITLE
Documentation:  Instructions for first-time developers

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#175]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

More information on tips and tricks for first time developers.  Links to onboarding videos might be helpful as well.

Perhaps this would live in the `Readme.md`

@esimms999-gsk please feel free to add on.

**Comment by esimms999-gsk** [comment]
I have been having trouble with setting up a new workspace environment when I want to do some development work on admiral, e.g. I forget that I need the devel version of admiraldev and admiral.test, must restart the session, etc. It would not be surprising if all of this is already documented, and I have been unaware of it ... or too lazy. :( 

I want to go through the available documentation on this and ensure it is easy to find and understand and that there are no gaps.

**Comment by esimms999-gsk** [comment]
A question I have: does Roche already have an image (Docker image?) of the environment that can be used by anyone who wants to work as a developer on admiral?

**Comment by bms63** [comment]
https://github.com/pharmaverse/admiraldev/issues/169
