### ISSUE TITLE
common workflows live here?

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#18]
@dinakar29 , I think the reusable workflows are great. I wonder if we should move the workflows to a separate repository and keep only `common.yml` in admiraltemplate. Otherwise, all the workflows will be copied if a new repository is created based on admiraltemplate.

_Originally posted by @bundfussr in https://github.com/pharmaverse/admiraltemplate/issues/27#issuecomment-1181647179_

**Comment by dinakar29** [comment]
Based on https://github.com/pharmaverse/admiraldev/issues/8#issuecomment-1189102647, I'll let the admiral working group  come to a consensus on this. Looks like not everyone is on the same page about this.

**Comment by dinakar29** [comment]
Based on https://github.com/pharmaverse/admiraldev/issues/8#issuecomment-1189102647, I'll let the admiral working group  come to a consensus on this. Looks like not everyone is on the same page about this.

**Comment by bms63** [comment]
A new repo is being created called admiralci that will house all the workflows for admiral  and extension packages.
https://github.com/pharmaverse/admiralci
