### ISSUE TITLE
Documentation: Update Roxygen Examples with library(pkg_name) rather than pkgname::function() documentation 

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiraldev#185]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

@bundfussr @bms63 

Similar to admiral Issue #1380 (Update Roxygen Examples with library(pkg_name) rather than pkgname::function() documentation), do we want to do the same thing in admiraldev? For example:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/85294667/203572034-00cf68f0-571d-46ea-be9b-7feae398e0e4.png">

**Comment by bms63** [comment]
Yes that is fine to call library(rlang) and library(dplyr)  to be consistent.
