### ISSUE TITLE
Documentation:  `assert_` functions missing roxygen documenation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#20]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

![image](https://user-images.githubusercontent.com/10111024/180289774-6ddbcee4-91f3-4f7b-bd95-a55e38bdacec.png)

These should have roxygen headers added to them

**Comment by bundfussr** [comment]
It seems that `assert_list_of_formulas()` is never used. Should we remove it?

**Comment by thomas-neitmann** [comment]
Yes, no need to keep legay code.
