### ISSUE TITLE
General Issue: Broken links in Development Process document

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiraldev#216]
### Background Information

There are a couple more broken links in the Development Process (https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) document 
When you click on both the *Contribution model* and *Adam template* both below leads a broken link
![image](https://user-images.githubusercontent.com/112789549/215937786-2cff90de-8c86-41f8-bca7-fc05549e43fe.png)
![image](https://user-images.githubusercontent.com/112789549/215938129-7fae4637-6e5f-40d5-b57e-4f1f373d9413.png)

Broken link for above 
![image](https://user-images.githubusercontent.com/112789549/215937595-f1b93fe9-8654-4edc-b0b3-49aec187c9f4.png)

### Definition of Done

- [x] Both links are working

**Comment by bms63** [comment]
Hi @MilesAlmond we are looking to release everything my March 6th.  Are you able to complete this in the next couple of days?
