### ISSUE TITLE
Bug: `assert_filter_cond()` is too restrictive

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#221]
### What happened?

`assert_filter_cond()` is too restrictive. Consider for example:
```
> paramcds <- c("A", "B")
> assert_filter_cond(expr(PARAMCD %in% !!paramcds))
Error in assert_filter_cond(expr(PARAMCD %in% !!paramcds)) :
is_expression(arg) is not TRUE
```

**Comment by bundfussr** [comment]
In the release notes for rlang 1.0.0 the following is stated.
>`is_expression()` now returns `FALSE` for manually constructed expressions that can’t be created by the parser. It used to return `TRUE` for any calls, including those that contain injected objects.
>
> Consider using `is_call()` or just remove the expression check. In many cases it is fine letting all objects go through when an expression is expected.

Therefore I have removed the `is_expression()` call in `assert_filter_cond()`.
However, I am not sure if `is_expression()` works as expected. Consider for example:
```
> vals <- "A"
> is_expression(expr(VAR %in% !!vals))
[1] TRUE
> vals <- c("A", "B")
> is_expression(expr(VAR %in% !!vals))
[1] FALSE
```
@thomas-neitmann , what do you think?

**Comment by zdz2101** [comment]
Seems to make sense, since the `is_call()` check comes a couple lines later too
