### ISSUE TITLE
Documentation:  How to display vignettes/documentation written for easier review

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiraldev#224]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

**Context:**
While writing up the Hy's Law implementation guide, team found it easier to:
 - Fork the admiral repo
 - Set up github-pages to be able to review vignettes via the webpage 

**Solution:**
Write up a step-by-step guide how exactly to set it up

**Comment by bundfussr** [comment]
A webpage for reviewing would be very helpful.
I wonder if it could be automated. Maybe a keyword or tickbox in the PR description could trigger a workflow which creates a webpage for the feature branch. If the PR is merged, another workflow removes the webpage.
@cicdguy , @bms63 , what do you think?

**Comment by rossfarrugia** [comment]
Hmm... i get the problem (as i remember a good example being where Ben had to try out a whole new look reference page before so he forked the repo and created and shared a separate test site for us all to check). my question would be how often is this really needed to justify adding yet another guide to our documentation? when i review a PR with a new vignette i usually just `build_site` or knit it myself in RStudio so i can examine how it'd look for the users. 

I guess i just worry that our developer guides are already so complex for new contributors, so i hesitate to add different approaches that might only confuse more. Especially when we have so many people that get involved who are new to GH.

Feel free to over-rule me @bms63 & @thomas-neitmann though here!

**Comment by rossfarrugia** [comment]
Fair, if it can be made really easy from an automation standpoint then i'd be ok with it. Like Stefan sayd if the user just needs to use some keyword in their PR or something like that, and they don't need to do any manual steps like taking a fork etc

**Comment by bms63** [comment]
Awesome - so we are going to look into setting this up this automation if a developers wants to display an updated vignette or some new novel documentation technique on the website?  @cicdguy shall I create an issue in `admiralci`? 

I think this is very handy for reviewing as it takes out the need for me to pull down and render content, which does take a few minutes.  

I'm definitely in agreement to make as little documentation around this need as it is a very niche use-case.  But I do think it needs a few blurbs in our dev documentation and use-cases of when something like this will be handy. 

@zdz2101 could we edit this issue to be more generic and not reference the fork process anymore.  For example, How to display vignettes and documentation for easier review??

**Comment by bms63** [comment]
@cicdguy and @dgrassellyb  do you all have bandwidth for this release to work on this ci solution?  

If not, we can implement our fork approach for temporary solution until you all have bandwidth?

**Comment by bms63** [comment]
Maybe the bot is a bit overkill?

We could just write it up in our Dev Docs and put the link in our PR template?

**Comment by bms63** [comment]
This was a nice idea, but seems like a lot of thought needs to go into it.  Just going to close it out.
