### ISSUE TITLE
Documentation:  Update to dplyr version in DESCRIPTION file

### ISSUE THREAD

**Issue by alanaharris22** [pharmaverse/admiraldev#246]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

The new release of admiraldev now has `dplyr::across` in the NAMESPACE file, this function is only available in `dplyr` versions greater or equal to 1.0.5 whereas the DESCRIPTION file refers to greater than or equal to 0.8.4 - not sure if this should be updated (caused some issues for us when working on the datacutr package which has admiraldev as a dependency).

**Comment by galachad** [comment]
That's true, we should update the minimum dplyr version to 1.0.0. Need to check if we should have compatibility with 0.8.4, or it should be 1.0 already. cc @bms63 @bundfussr

**Comment by bundfussr** [comment]
There were several bug fixes for `across()` after 1.0.0. Therefore I would set the minimum version to 1.0.5. For 1.0.0 some of our tests fail.
