### ISSUE TITLE
Feature Request: Clean up assertions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#264]
### Feature Idea

The assertion functions should be reviewed and duplicates and functions which are no longer used should be removed. For example `assert_function()` covers `assert_function_params()`.

**Comment by zdz2101** [comment]
0 | asserts
-- | --
1 | assert_character_scalar
2 | assert_vars
3 | assert_logical_scalar
4 | assert_data_frame
5 | assert_s3_class
6 | assert_list_of
7 | assert_function_param
8 | assert_numeric_vector
9 | assert_character_vector
10 | assert_date_vector
11 | assert_integer_scalar
12 | assert_symbol
13 | assert_function
14 | `assert_db_requirements
15 | `assert_terms
16 | assert_db_requirements
17 | assert_terms
18 | assert_varval_list
19 | assert_param_does_not_exist
20 | assert_expr
21 | assert_filter_cond
22 | assert_unit
23 | assert_expr_list
24 | assert_same_type
25 | assert_list_element
26 | assert_one_to_one
27 | assert_date_var
28 | !!assert_expr
29 | assert_named_exprs
30 | [assert_valid_queries
31 | assert_valid_queries
32 | assert_has_variables
33 | `assert_one_to_one

**Comment by zdz2101** [comment]
Is `assert_s3_class()` redundant to `assert_function_param()` and `assert_list_of()` based on these instances? @bundfussr 
![image](https://github.com/pharmaverse/admiraldev/assets/43018762/c8ca3ac2-0e1b-4dae-b700-d0f82c77be4e)

**Comment by zdz2101** [comment]
@pharmaverse/admiral 

Looks like
1. `assert_function()` covers `assert_function_params()`
2.  `assert_date_var()` and `assert_date_vector()` do relatively similar things, ie check for `is.instant()` most likely can be consolidated?
3. `assert_date_frame()` 's argument `required_vars` looks like it covers `assert_has_variables()` 
4. `assert_named_expr()` is only used in `admiral::derive_basetype_records()`, but looks like it can be swapped with `assert_expr_list()`

Proposed decision is the deprecate:

- `assert_function_params()` 
- one of `assert_date_var()`/`assert_date_vector()` (based on naming convention I like _vector more)
-  `assert_has_variables()`
-  `assert_named_expr()`

**Comment by bms63** [comment]
> @pharmaverse/admiral, what do you all think? Ping me for mural access (didn't want to link it on this github issue)
> 
> Looks like
> 
> 1. `assert_function()` covers `assert_function_params()`
> 2. `assert_date_var()` and `assert_date_vector()` do relatively similar things, ie check for `is.instant()` most likely can be consolidated?
> 3. `assert_date_frame()` 's argument `required_vars` looks like it covers `assert_has_variables()`
> 4. `assert_named_expr()` is only used in `admiral::derive_basetype_records()`, but looks like it can be swapped with `assert_expr_list()`
> 
> Proposed decision is the deprecate:
> 
> * `assert_function_params()` 
sounds good to me
> * one of `assert_date_var()`/`assert_date_vector()` (based on naming convention I like _vector more)
I like `vector` more as well
> * `assert_has_variables()`
umm...do you think we might need this...i can't think of any reason...
> * `assert_named_expr()`
sounds good to me

**Comment by zdz2101** [comment]
![image](https://github.com/pharmaverse/admiraldev/assets/43018762/2a1f3daa-6fc1-4d7c-a62d-0eb924b87441)

@pharmaverse/admiral After investigating a little more into how each of `assert_date_var/assert_date_vector` is used in admiral, there are slightly different use cases, side-by-side screenshot of code for reference above. 

- `assert_date_var` is used frequently in loops where there are multiple source datasets, in which the assertion becomes useful in providing messaging for indexing which columns from which dataframes there might be an issue with date/datetime
- `assert_date_vector` is used frequently in `compute_` function where there's no direct tie to a dataframe in the arguments

As such, I'm unsure if there is a need to deprecate the `assert_date_*` functions although I can't help but think these two still can be combined somehow, perhaps a better task would be to leave better documentation when to use each one?

**Comment by bundfussr** [comment]
@zdz2101 , what about `assert_varval_list()`? I wonder if it should be deprecated in favor of `assert_expr_list()`.
