### ISSUE TITLE
Idea for future: Any way to automate adding default argument values in roxygen headers?

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiraldev#270]
We'd like a way to take this info directly from the Usage box rather than manually repeating the info:

![image](https://user-images.githubusercontent.com/82581364/187701587-775b8cd2-a711-4e56-9a26-c8fcb0e76adb.png)

Any clever ideas from the admiral community for this?? For now we're going to remove the repeated default values under the arguments section as it's difficult to maintain and subject to manual error.

**Comment by zdz2101** [comment]
Closing to centralize as denoted in https://github.com/pharmaverse/admiraldev/issues/290
