### ISSUE TITLE
Documentation:  Add new Developer Guide page "Test Data Guidance"

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiraldev#282]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

Page should detail how any test data for an {admiral<TA>} package should be included in the new package {admiraldata}, and also describe how to create it, where to store it, and with what name.

**Comment by bundfussr** [comment]
We should describe using and creating vignette data in the new vignette (see https://github.com/pharmaverse/admiral/discussions/1980#discussioncomment-6434990).
