### ISSUE TITLE
Documentation:  roxygen documenation missing for `%or%

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#29]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Do we need this?  If so, we should document it.

**Comment by thomas-neitmann** [comment]
Yes, this function is needed. It allows to string together two `assert_*()` functions. If the first one is throwing an error it catches that and only let it through it the second assertion also fails, e.g. `assert_something() %or% assert_something_else()`.

**Comment by sadchla-codes** [comment]
@bms63 it appears that this function has been documented but not link to any PR 
![documentation update](https://user-images.githubusercontent.com/112789549/204067777-724aae41-bc96-4efd-8d12-9480a77c3efe.png)

**Comment by bms63** [comment]
Probably in the rush to get this package out to CRAN last time.  I will close it.
