### ISSUE TITLE
Documentation: Create guidance around making templates

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#295]
We do not provide any guidance to extension packages or to core team around creating a template for ADaMs. 

## Prep Work

- [ ] Review templates in core and extension packages for potential best practices
- [ ] Review templates in core and extension packages for not so great practices
- [ ] Sketch out Best Practices Guidance on Template creation and present to core team
- [ ] Discuss with core team best location for guidance (section in one vignette or separate vignette)
 
## Definition of Done
- [ ] Write a new vignette (or section of existing vignette) with guidance for creating a template.  

Quote from referenced issue #293 :
>In principle, we should also add something to the templates guidance but we do not have any. Should we add one?
> 
> What do you mean by template guidance?

We provide several templates in `inst/templates` but we do not have a guidance for these files, e.g., we do not describe when templates should be created, how they should be structured, which data they should use, ...

_Originally posted by @bundfussr in https://github.com/pharmaverse/admiraldev/issues/293#issuecomment-1619963647_

**Comment by bms63** [comment]
@manciniedoardo and @bundfussr what do you think?  Feel free to edit.

**Comment by manciniedoardo** [comment]
This template vignette should additionally refer to the [Programming Strategy](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html) vignette on admiraldev, as it explains lots of the code conventions that are used.
