### ISSUE TITLE
General Issue: `dataset_ref`, `dataset_add` and `dataset_adxx` add to list of common arguments

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#306]
### Background Information

As part of our efforts to get to a `1.0` version of `admiral`, we are looking over all functions for consistency and user-friendliness. As developers we should strive to maintain a consistent list of arguments in our development documents that can be used within our functions to help with creation of new functions as well as maintenance.

https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#list-of-common-arguments

The arguments `dataset_ref`, `dataset_add` are missing from the list/table.  These should be added with a text on the difference between the two.  Please review functions using these arguments to gain understanding of the difference.

The argument `dataset_xxxx` should be added to the list/table.  This is a unique argument for function that expect a certain type of dataset and variables in order to be used.  For example, derive_vars_atc requires the facm dataset with required variables.  

![image](https://github.com/pharmaverse/admiraldev/assets/10111024/7776acbb-17e5-41eb-bca2-78d0a91e1d7b)

### Definition of Done

- [ ] Arguments added to the list/table  `dataset_ref`, `dataset_add` and `dataset_adxx` with succinct and informatioive description

**Comment by StefanThoma** [comment]
`dataset_adxx` appears as an argument only in three functions. 
```
./derive_param_tte.R                       9     #' @param dataset_adsl ADSL input dataset
./derive_param_extreme_event.R 17     #' @param dataset_adsl ADSL input dataset
./derive_param_exist_flag.R         94     #' @param dataset_adsl *Deprecated*, please use `dataset_ref` instead.
```
As you can see, it is always `dataset_adsl`. 
However, in one function this is already deprecated. 
Should we deprecate in favour of `dataset_ref` as well? Would that fit?

**Comment by StefanThoma** [comment]
Also, I still have some confusion as to the exact difference between the dataset_ref and dataset_add and dataset.
I have some idea, but am not exactly sure whether its true. 
Ill upload a draft version, would be happy for feedback.

**Comment by bms63** [comment]
Hi @StefanThoma.

@bundfussr wrote a nice summary of the differences here - https://github.com/pharmaverse/admiral/discussions/2010#discussioncomment-6528564
