### ISSUE TITLE
Feature Request:  Bash helpers

### ISSUE THREAD

**Issue by StefanThoma** [pharmaverse/admiraldev#309]
### Feature Idea

Add some simple bash commands to the developers guide.
I think this could be quite useful, e.g. for the deprecation strategy I was able to use: 

`find . -type f ! -path "./man/*" ! -path "./inst/*" ! -path "*/.*" -exec grep -nH "compute_egfr(" {} + | awk -F ':' '{printf "%-30s %-5s %s\n", $1, $2, $3}'
`
To find all instances of the function "compute_egfr(" in admiral when deprecating one of its arguments, making the process much faster.

### Relevant Output

Relevant bash commands in the developers guide for improved dev workflow.

### Reproducible Example/Pseudo Code

`find . -type f ! -path "./man/*" ! -path "./inst/*" ! -path "*/.*" -exec grep -nH "compute_egfr(" {} + | awk -F ':' '{printf "%-30s %-5s %s\n", $1, $2, $3}'`

**Comment by bms63** [comment]
Hi Stefan.  Are you able to take this on?

I don't have a lot of linux commands I use except `grep`, `awk`, `||` or `>` .  Maybe we could just make a general reference that developers should check out some linux basics to speed up search and replaces rather than making any guidance around it?

**Comment by bms63** [comment]
Going to close this out
