### ISSUE TITLE
Documentation:  Release Process as its own vignette

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#33]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

Since we have more room, we should split out some the vignettes to make it easier to find things and keep things fresh

Starting with vignette for release process - the really nit and gritty

**Comment by zdz2101** [comment]
Was this already accomplished with [#112](https://github.com/pharmaverse/admiraldev/pull/112) ? @rossfarrugia @bms63

**Comment by bms63** [comment]
Yes nice catch
