### ISSUE TITLE
Feature Request: Allow grouped dataframes in `process_set_values_to()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#331]
### Feature Idea

Allow grouped dataframes in `process_set_values_to()`.

**Comment by bms63** [comment]
Does this break our prohibition on input datasets being grouped?

![image](https://github.com/pharmaverse/admiraldev/assets/10111024/15a99031-50e9-48bf-9a73-ce1d1cd59fe8)

Actually maybe we need to revisit all these points?

**Comment by bundfussr** [comment]
> Does this break our prohibition on input datasets being grouped?
> 
> ![image](https://user-images.githubusercontent.com/10111024/268992239-15a99031-50e9-48bf-9a73-ce1d1cd59fe8.png)
> 
> Actually maybe we need to revisit all these points?

I think we had exceptions before. However, maybe we do not need it because I changed the code in the related admiral code.

**Comment by bundfussr** [comment]
Not needed
