### ISSUE TITLE
Feature Request: assert_data_frame() should state argument name in error message

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#352]
### Feature Idea

At the moment the argument name is included in the error message of `assert_data_frame()` if the argument is of wrong type but not if a required variable is missing:
```
> assert_data_frame(dataset <- 1, required_vars = exprs(USUBJID))
Error in `assert_data_frame()`:
! `dataset` must be a data frame but is `1`
Run `rlang::last_trace()` to see where the error occurred.
> assert_data_frame(dataset <- data.frame(STUDYID = "XYZ"), required_vars = exprs(USUBJID))
Error in `assert_data_frame()`:
! Required variable `USUBJID` is missing
Run `rlang::last_trace()` to see where the error occurred.
```
This should be changed as many admiral functions have more than one input/source dataset. Thus it is not clear to which dataset the message is referring to.

**Comment by Fanny-Gautier** [comment]
We are always getting 'dataset' instead of the argument's name. Is it ok to change a little bit the error message to include the function causing troubles instead ? Please see below screenshot as an example.
![image](https://github.com/pharmaverse/admiraldev/assets/157114584/b8400c20-03ab-493a-b59b-b2ddb528aebf)

**Comment by bms63** [comment]
Hi all - There is an effort to improve the error messaging for all functions in admiral and so this issue fits under that group's purview.  I believe this will be a big task to tackle!!  Do you want to join in?  We are just getting started. 

https://pharmaverse.slack.com/archives/C028SJ83KM1/p1707323912055529

I am going to close this issue and we will make more focused ones after our planning sessions are done.

**Comment by bundfussr** [comment]
> I am going to close this issue and we will make more focused ones after our planning sessions are done.

I think this issue is already very focused. Why should we close it?

I would expect that the improving error messaging effort results in many issues like this one.

**Comment by bms63** [comment]
Agree that this is going to be one of the functions we update from the Error Group, but to me it isn't very clear what we are doing under the hood for this update.   

- Are we doing the update with suggested `cli` improvements or will this one be separate from the others with just a quick fix for now?  
- Do the tests need to be updated after the improvement is made?  I would think so?  
- How is adjusting the underlying assert statement going to impact other admiral functions?  
  - Is the person responsible for assessing the impact on every admiral function? 
  - Will they make updates to other functions or tests?
- Will the change break anything additional in extension packages?

Just was thinking that the Error messaging group would have a more prescriptive approach after we meet to discuss and this issue and would be "resurrected" with more direction in a new issue.
