### ISSUE TITLE
General Issue: Update hotfix process

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#361]
### Background Information

https://stackoverflow.com/questions/10940981/how-to-create-a-new-branch-from-a-tag

@zdz2101 let's jot down our notes here and update hotfix process before we forget!!

**Comment by bundfussr** [comment]
We have already a PR for the update of the release processes: https://github.com/pharmaverse/admiraldev/pull/354

**Comment by bms63** [comment]
Righto!!!!
