### ISSUE TITLE
General Issue: `valid_time_units` the same as `is_timeunit`?

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#37]
### Background Information

These look to be doing similar things.  one is robustly documented and other is not.  Do we need the undocumented function?  

Is the undocumented function used in admiral?  Yes, in derive_vars_duration.  

![image](https://user-images.githubusercontent.com/10111024/183504728-df086127-6148-4eac-ad62-d81ff72c5cd5.png)

![image](https://user-images.githubusercontent.com/10111024/183504771-c10ad1b7-5b63-43d4-8651-cb59d49aef9e.png)

### Definition of Done

Keep or remove valid_time_units?

If we keep, then update roxygen documentation for this function.

**Comment by bms63** [comment]
@thomas-neitmann @bundfussr thoughts?

**Comment by bundfussr** [comment]
I would remove `is_timeunit()`. It is called in `compute_duration()` only. I think it is more consistent to replace `assert_that(is_timeunit(in_unit))` with `assert_character_scalar(in_unit, values = valid_time_units())`.

**Comment by thomas-neitmann** [comment]
I agree with @bundfussr.

**Comment by bms63** [comment]
K I think I'm going to say this is for  the next release of admiraldev 0.2.0
