### ISSUE TITLE
General Issue: Undocumented function within `is_order_vars`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#38]
### Background Information

![image](https://user-images.githubusercontent.com/10111024/183508360-819a2d56-499e-4b8c-b8b2-c032a8785c7a.png)

`quo_is_desc_call` is used within `is_order_vars`.  Do we want to separate out this function so it can be used other places if needed, provide context on what it is, easily test it, etc.

### Definition of Done

Decide if we want to split out this function.

If yes, set up documentation and test the function

**Comment by bms63** [comment]
@thomas-neitmann @bundfussr What are your thoughts?

**Comment by bundfussr** [comment]
It would be cleaner to split it but `quo_is_desc_call()` is quite specific. So it is unlikely that it is used outside of `is_order_vars()`.
Thus I am not sure if it is worth the effort.
@thomas-neitmann , what do you think?

**Comment by thomas-neitmann** [comment]
I defined it locally inside the outer function because that's the only place where it's used. Usually I would have used an anonymous function inside `map_lgl()` but this one got quite big so I chose to separate it out.
