### ISSUE TITLE
Documentation:  `contain_vars` is in need of roxygen documentation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#39]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

`contain_vars` within the `dev_utils.R` file is in need of roxygen documentation

**Comment by sadchla-codes** [comment]
@bms63  I'm having trouble finding `contain_vars` in `admiraldev`
![contain_var2](https://user-images.githubusercontent.com/112789549/196995014-b431bf40-93bf-484e-91b0-d6f7fb57ba2c.png)
