### ISSUE TITLE
General Issue: Bring over all assert functions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#4]
### Background Information

admiral has assert functions and asset_that functions in several files.  These should be confirmed and brought over.

### Definition of Done

All tests and functions related to the assert should be brought over to admiraldev

**Comment by thomas-neitmann** [comment]
Please make sure to first add these functions to {admiraldev} and only once they make it to the `devel` branch to delete them in {admiral}. Same for #3.

**Comment by bundfussr** [comment]
Shouldn't we deprecate the functions in admiral?

**Comment by thomas-neitmann** [comment]
I'm not sure. While (at least some of) them were exported they were not meant for users so I doubt anyone actually made use of them. So deprecating them might be overkill. However, if we want to be on the safe side then we could also follow our usual deprecation guidance.

**Comment by bundfussr** [comment]
We use many of these functions in admiralonco and admiralroche. These packages would break if we just remove the functions from admiral. However, so far these packages were not officially released. So it may be acceptable. I do not know if anyone else has used the functions to implement user-specific functions in admiral style. Any idea?

**Comment by bms63** [comment]
## Relocation Strategy

I was thinking we would use the same  strategy as we did for `derive_suppqual` where we removed the function contents from `admiral` but had a message saying to see `comine_supp` in `metatools`.  This message would appear for one release cycle.

I also made keyword/family combo that lets us group all these functions being moved into one category on the reference page.  
![image](https://user-images.githubusercontent.com/10111024/179221646-8410838a-db76-4a67-8f1e-1cec31daff3f.png).  This might also be handy for us all to look at and review as some of the functions might need to just stay in admiral.

## Breaking things

> We use many of these functions in admiralonco and admiralroche. These packages would break if we just remove the functions from admiral. However, so far these packages were not officially released. So it may be acceptable. I do not know if anyone else has used the functions to implement user-specific functions in admiral style. Any idea?

I was envisioning that once `admiraldev` is stable then we can install it from github for the three packages (core, onco, roche) and see what issues arise.  I'm unclear of what will happen when for example  `assert_dataframe` appears in `admiral` and `admiraldev`.  Perhaps we can use the `reexports.R` to deal with this?

**Comment by bundfussr** [comment]
This could be tricky. I think we would need to ensure that `admiraldev` is loaded after `admiral`.

**Comment by bundfussr** [comment]
I agree. It seems we have no other choice.

**Comment by bms63** [comment]
@SyedMubasheer  I started to have a go with this, but it is not complete.  Please branch off `devel` and have a go.

**Comment by SyedMubasheer** [comment]
> @SyedMubasheer I started to have a go with this, but it is not complete. Please branch off `devel` and have a go.

Sure @bms63!
