### ISSUE TITLE
Re-export `rlang::is_named()` ?

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiraldev#401]
We re implementing our own version of `is_named()` that masks `rlang::is_named()` when both packages are loaded. it seems to me that it's doing the same thing. Perhaps we should just reexport the rlang function instead.

**Comment by bundfussr** [comment]
Good point.

I am not sure if we need to reexport it. Most likely just importing it is fine.

**Comment by bms63** [comment]
There was some reason we did this, but it eludes me.  I think we meant to document it in the `is` file. 

I'm wondering if we can remove this stuff as well https://github.com/pharmaverse/admiraldev/blob/66a59b0c601ce322841e8296634de9cb9183bc59/R/compat_friendly_type.R - I think this is from an older version of rlang

**Comment by ddsjoberg** [comment]
Some of the current `assert_*()` functions use functions in `compat_friendly_type.R`. But after the messaging updates, we can take a look if it's still being used somewhere. I updated the checklist in the issue tracking the assert messaging updates to check this at the end of the big update.

<img width="813" alt="image" src="https://github.com/pharmaverse/admiraldev/assets/26774684/5010fb2e-f044-499d-8b79-e1f24f8d3378">
