### ISSUE TITLE
`assert_function` Error Msg: Provide user with possible correct argument/syntax to the user what they are missing?

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#413]
Is there anyway to recommend to the user what they are missing?

![image](https://github.com/pharmaverse/admiraldev/assets/10111024/735d8528-2523-4135-829b-5f8907339976)

For example, here I put in filter, but it should be filter_add?

Like a "Did you mean - filter_add" or if nothing else list out the possible arguments available to the function?

_Originally posted by @bms63 in https://github.com/pharmaverse/admiraldev/pull/399#pullrequestreview-1954907043_

**Comment by ddsjoberg** [comment]
@bms63 R allows for position matching for arguments and partial name matching. There are options a user can specify (or a company could set this) if they didn't want to allow for these "conveniences". But do we want to enforce a change to low-level R behavior?

In the example above `filter` would be a partial match for `filter_add`. I think this kind of change should happen at the user level, so users don't experience differential behavior even across admiral functions.

**Comment by bms63** [comment]
Yeah - we shouldn't enforce this at our level.  Thanks for looking into.  We can close this one out.
