### ISSUE TITLE
General Issue: Addin for testthat formatting appearing in dropdown

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#419]
### Background Information

I just realized that this Addin appears after installing admiral.  Is there a way to suppress this and only install it for developers when needed?  Any tricks @pharmaverse/admiral ?

![image](https://github.com/pharmaverse/admiraldev/assets/10111024/acc655cf-67df-4238-959f-4075c19d38be)

### Definition of Done

- [x] Suppress Addin for the testthat functionality when a user installs admiral
- [x] Make it easy for a developer to use the Addin
  - How do to this? Prompt when you install admiraldev??
- [x] Update Unit Test Guidance

**Comment by ddsjoberg** [comment]
I don't anticipate this being a popular idea....but do we need an add-in for numbering tests? I love that we've sectioned them off, but the numbering could be more than we need and has caused unnecessary merge conflicts in the very recent past.

**Comment by bms63** [comment]
@ddsjoberg  

![image](https://github.com/pharmaverse/admiraldev/assets/10111024/29542449-ad2c-435c-a138-2e2c05d0ae32)

**Comment by ddsjoberg** [comment]
Another alternative would be to move the addin code to another package that users don't install, e.g. `admiraldev4devs` 😉 The package does **not** need to go to CRAN. But any dev who is working with/updating unit tests that are numbered will need to know the package exists, and to install it. Not ideal, but I still think it's preferable to cluttering every users add-in menu with functionality they will never use.

**Comment by ddsjoberg** [comment]
Goal is to have this complete before the June release. Thanks @sadchla-codes !
