### ISSUE TITLE
`assert_one_to_one()` (depends on `assert_vars()`, `assert_data_frame()`)

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiraldev#424]

**Comment by ddsjoberg** [comment]
@bms63 i was late to this week's stand up, and when I arrived the team was discussing this function. Is it good to be converted to {cli}, or is there a blocker for this one?

**Comment by bms63** [comment]
We decided to not implement `assert_one_one()` in more of our admiral functions as it was observed to cause some headaches in other extension packages (@bundfussr).  

I believe @manciniedoardo was going to work on some updates in our vignettes on some pre-processing/post processing 1-1 checks available in the Roche templates.  It might get a mention in the Simple Walkthrough guides as well.  https://github.com/pharmaverse/admiral/issues/2395

So NO BLOCKERs

![image](https://github.com/pharmaverse/admiraldev/assets/10111024/ae053602-cf85-4d0c-a86a-5c3919736054)
