### ISSUE TITLE
General Issue: `on_failure` nested function

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#43]
### Background Information

A lot of the `is` functions have a nested `on_failure` function within them.  Do we want to split this out?  I see most of them follow the same pattern, but a few differ.

![image](https://user-images.githubusercontent.com/10111024/183514099-8d6e0d7e-0fe1-490d-9c88-9e44a91934db.png)

**Comment by bms63** [comment]
@thomas-neitmann @bundfussr thoughts?

**Comment by bundfussr** [comment]
This pattern is the way how `assert_that()` works. Over time we moved away from using `assert_that()`. I am not sure if we should remove the `assert_that()` calls completely. @thomas-neitmann , what do you think?

**Comment by thomas-neitmann** [comment]
I'd like to remove all `is_*()` functions and get rid of the {assertthat} dependency. Ideally we only have our "custom" `assert_*()` functions as part of {admiraldev}.

**Comment by sadchla-codes** [comment]
@bms63 @thomas-neitmann @bundfussr  I think https://github.com/pharmaverse/admiraldev/issues/149#issue-1427282083 and https://github.com/pharmaverse/admiraldev/issues/147#issue-1424665239 are aiming to address the same issues so here is my observation and questions related to this

- it seems like most of the {assertthat} function are in the `is_*.R` programs, so are the desires to remove `is_*()` functions something we would like to do overtime? or can I deprecate them now? ... Based on my search result, it doesn't look like {admiral} is using any `is_*` functions so there would not be any downstream consequence,  
- if we are fading `is_*()`  overtime, should https://github.com/pharmaverse/admiraldev/issues/149#issue-1427282083 and https://github.com/pharmaverse/admiraldev/issues/147#issue-1424665239 be tagged for a different release?
- I'm (of course) open to other ideas or suggestions.

**Comment by bms63** [comment]
> @bms63 @thomas-neitmann @bundfussr I think [#149 (comment)](https://github.com/pharmaverse/admiraldev/issues/149#issue-1427282083) and [#147 (comment)](https://github.com/pharmaverse/admiraldev/issues/147#issue-1424665239) are aiming to address the same issues so here is my observation and questions related to this
> 
> * it seems like most of the {assertthat} function are in the `is_*.R` programs, so are the desires to remove `is_*()` functions something we would like to do overtime? or can I deprecate them now? ... Based on my search result, it doesn't look like {admiral} is using any `is_*` functions so there would not be any downstream consequence,
> * if we are fading `is_*()`  overtime, should [General Issue: Removing dependency on {assertthat} to match with {admiral} #149 (comment)](https://github.com/pharmaverse/admiraldev/issues/149#issue-1427282083) and [Documentation:  Remove mentions of {assertthat} in pkgdown website #147 (comment)](https://github.com/pharmaverse/admiraldev/issues/147#issue-1424665239) be tagged for a different release?
> * I'm (of course) open to other ideas or suggestions.

We do want to get rid of the `is_*` functions and have the `assert` functions covering this need.  

If we are not using any of the `is_` function, then we should just remove them from `admiraldev` for this release cycle.  But can you double check this in `admiral` and `admiralonco` as well and make sure they are not using them?

Can you add an item to the Meeting agenda for Wednesday for us to discuss.
