### ISSUE TITLE
Update `unit_test_guidance.Rmd` to remove the `arg_name()` example

### ISSUE THREAD

**Issue by ddsjoberg** [pharmaverse/admiraldev#436]
The `arg_name()` is now deprecated

**Comment by ddsjoberg** [comment]
Hi @sadchla-codes @kaz462 @millerg23 @manciniedoardo @bms63 @bundfussr 

As part of the error messaging update, we deprecated `arg_name()`. Do any of you have the bandwidth to make this corresponding update to our documentation?

**Comment by bms63** [comment]
😭
