### ISSUE TITLE
Feature Request:  provide `assert_logical_vector()`

### ISSUE THREAD

**Issue by ramiromagno** [pharmaverse/admiraldev#455]
### Feature Idea

 While developing sdtm.oak we found it useful to have an assertion function for logical vectors, e.g. `assert_logical_vector()`.

**Comment by bms63** [comment]
@ramiromagno thanks for the suggest!  Am I to understand that you all developed something like this in sdtm.oak?  Care to share it with us?

**Comment by bms63** [comment]
Thanks @ramiromagno!  @pharmaverse/admiral what do you think?

**Comment by ddsjoberg** [comment]
Hmmm, I am a bit torn. If admiraldev were a package set up to provide generic checks, then absolutely yes.

But it's a package meant to support admiral, so I am hesitant to expand the scope in that direction. Moreover, we've had informal discussions about migrating admiraldev back into admiral. If that were to happen, then sdtm.oak would have to take on a bigger dependency to continue using these functions.

With a few open questions on this point, @ramiromagno do you think it may be best to add the function directly to your package for now? Something like this would work, or you could make a variant just for logical vectors

``` r
check_class <- function(x,
                        cls,
                        allow_empty = FALSE,
                        message =
                          ifelse(
                            allow_empty,
                            "The {.arg {arg_name}} argument must be class
                             {.cls {cls}} or empty, not {.obj_type_friendly {x}}.",
                            "The {.arg {arg_name}} argument must be class
                             {.cls {cls}}, not {.obj_type_friendly {x}}."
                          ),
                        arg_name = rlang::caller_arg(x),
                        class = "check_class",
                        call = parent.frame(),
                        envir = rlang::current_env()) {
  # if empty, skip test
  if (isTRUE(allow_empty) && rlang::is_empty(x)) {
    return(invisible(x))
  }
  
  if (!inherits(x, cls)) {
    cli::cli_abort(message, class = c(class, "standalone-checks"), call = call, .envir = envir)
  }
  invisible(x)
}

check_class(c(TRUE, FALSE), cls = "logical")
check_class(letters, cls = "logical")
#> Error:
#> ! The `letters` argument must be class <logical>, not a character
#>   vector.
```

<sup>Created on 2024-06-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ramiromagno** [comment]
Hi @bms63 and @ddsjoberg,

The function in question is already included in our package, sdtm.oak. In fact, the suggestion to raise this issue originated from another developer at sdtm.oak. Our team has been operating under the assumption that admiraldev serves as a foundational package for the CDASH -> SDTM -> ADaM continuum, and we have been leveraging it wherever possible to avoid duplicating efforts, particularly for fundamental assertions.

However, if the intent is for admiraldev to be a closer companion specifically to admiral, and other packages should minimize dependencies on it, we can adapt accordingly. For us at sdtm.oak, it should not be overly challenging to start integrating these functions directly into our package.

**Comment by bundfussr** [comment]
In principle we shouldn't have such general checks like `assert_logical_scalar()` in admiraldev because they are not admiral specific. However, I see no value in moving our general checks into a separate general package or removing the general checks from admiraldev and using other packages like `checkmate`. Thus I would leave it as it is.

@ramiromagno , if you don't want to implement `assert_logical_vector()` in your package (or remove it from your package), you could use `checkmate::assert_logical()`.

**Comment by ramiromagno** [comment]
Hi Stefan,

Thanks for the checkmate suggestion. Actually, the team decided to go with admiraldev instead of checkmate for these kind of assertions. But understanding now how you regard admiraldev as very closely related to admiral only we might start changing that.
