### ISSUE TITLE
General Issue: Remove `quosures` argument in `vars2chr()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#458]
### Background Information

The  `quosures` argument in `vars2chr()` was deprecated in admiraldev 0.5.0. Thus it should be removed (or should have been removed in admiraldev 1.1.0).

Also check for other arguments or functions which should have been removed.

**Comment by ProfessorP-beep** [comment]
I'll take a look this week.

**Comment by ProfessorP-beep** [comment]
Sorry, got caught up at work. Working on this now.

**Comment by bms63** [comment]
This got fixed in #464
