### ISSUE TITLE
Feature Request: Allow more than one unit for `required_unit` in `assert_unit()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraldev#468]
### Feature Idea

Allow more than one unit for `required_unit` in `assert_unit()` (see https://github.com/pharmaverse/admiral/issues/2513).

Additionally:
- Make `required_unit` optional. If not specified, only the uniqueness of the unit in the input dataset is checked.
- Document the uniqueness check.
- Document the required variables (`PARAMCD`) in the description of the `dataset` argument.

**Comment by yurovska** [comment]
@bundfussr In addition to allowing more than one unit for `required_unit`, it would also be great if we could use `assert_unit()` with `required_unit` being optional, so that it only performs the check for multiple units within a parameter, i.e. without a restriction of what that unit is.

**Comment by bundfussr** [comment]
> @bundfussr In addition to allowing more than one unit for `required_unit`, it would also be great if we could use `assert_unit()` with `required_unit` being optional, so that it only performs the check for multiple units within a parameter, i.e. without a restriction of what that unit is.

@yurovska , good idea. I've updated the description.

**Comment by manciniedoardo** [comment]
@bundfussr do you have capacity to knock this one out in the next week or two pls? then we can integrate the update within admiralmetabolic ahead of its first release.

**Comment by bundfussr** [comment]
> @bundfussr do you have capacity to knock this one out in the next week or two pls? then we can integrate the update within admiralmetabolic ahead of its first release.

Yes, no problem.
