### ISSUE TITLE
Documentation:  Vignettes language should be generalized to the admiral family/extensions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#48]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

Language is very specific to admiral-core, but admiraldev is intended for all packages.  We should reflect this generalization in the language we use within the vignettes.

**Comment by sadchla-codes** [comment]
@bms63 is this referring to the programming strategy vignette or all vignettes?

**Comment by bms63** [comment]
Programming Strategy for admiraldev and other related vignettes that are on admiraldev

**Comment by bms63** [comment]
Close as no longer needed
