### ISSUE TITLE
General Issue: Site should publish from devel branch and not main branch

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#49]
### Background Information

As we develop our programming processes, we should keep these updated in the website for all core and extension packages to see.  Rather than releasing updated website at every CRAN release, we should update it from devel so it stays current.

### Definition of Done

pkgdown action is switched to devel

**Comment by bms63** [comment]
Is this something we could set this week @cicdguy ?

**Comment by cicdguy** [comment]
Yes, change will be made shortly.
