### ISSUE TITLE
Move utility functions from admiralonco over

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiraldev#55]
See https://github.com/pharmaverse/admiralonco/issues/100

**Comment by rossfarrugia** [comment]
@thomas-neitmann @bundfussr @bms63 i'm looking further into this and `count_vals`, `max_cond`, `min_cond` i guess will all be taken care of as they already had moved from admiralonco -> admiral. 

i'm assuming `filter_confirmation` would stay in admiral, and `filter_pd` would stay in admiralonco.

then the only one left in admiralonco would be `aval_resp` - which is very onco specific so personally i would leave it, but happy to move that here if you feel like we should stick to the rule of all utility functions always living in admiraldev.

let me know thoughts!

**Comment by thomas-neitmann** [comment]
> i'm looking further into this and count_vals, max_cond, min_cond i guess will all be taken care of as they already had moved from admiralonco -> admiral.

I wasn't aware of that. Is there a PR for including these function in {admiral}?

> i'm assuming filter_confirmation would stay in admiral, and filter_pd would stay in admiralonco.

Agree.

> then the only one left in admiralonco would be aval_resp - which is very onco specific so personally i would leave it, but happy to move that here if you feel like we should stick to the rule of all utility functions always living in admiraldev.

I'd suggest to keep it in {admiralonco}.

**Comment by rossfarrugia** [comment]
Thanks Thomas! On the last point, if the others agree then i could close this issue and delete the branch i had started.

For the admiral PR for your first question see https://github.com/pharmaverse/admiral/pull/1294
