### ISSUE TITLE
General Issue: Clarify process for assigning authors and contributors in Description File

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#61]
### Background Information

Clarify process for assigning authors and contributors in Description File

### Definition of Done

* Developer Vignette gives guidance on how to assign someone as an author or contributor
* Developer Vignette gives guidance on how to move someone from author to contributor/contributor to author.

**Comment by manciniedoardo** [comment]
See [here](https://github.com/pharmaverse/admiral/issues/1941) for a proposed strategy.
