### ISSUE TITLE
Documentation: Clarity on documentation of function arguments

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiraldev#64]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

See discussions at https://github.com/pharmaverse/admiralonco/issues/130 and https://github.com/pharmaverse/admiraldev/issues/72. 

Needs to be summarized in our programming strategy under "Function Header (Documentation)" section. 

For permitted values include a controlled terminology list of possible options so that we don't end up with each developer writing "a source object" vs "an R6 object" ... etc when meaning the same thing for this field.

**Comment by zdz2101** [comment]
Closing to centralize as denoted in https://github.com/pharmaverse/admiraldev/issues/290
