### ISSUE TITLE
General Issue: Develop a release strategy for admiraldev

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#7]
### Background Information

The functions within `admiraldev` are used in core, onco and roche packages.  We need to think on how to deploy this package and how to deal with potential issues that  could arise. 

For example, one issue is where the `assert_data_frame` will now appears in multiple packages and how to only use the one from `admiraldev`.  

* When is this package deemed stable on Github
* When do we release this package to CRAN?

### Definition of Done

Release Strategy developed

**Comment by thomas-neitmann** [comment]
We should get this on CRAN prior to our next {admiral} release, preferably a week or two before. After the initial release we should simply follow {admiral}'s release cycle.
