### ISSUE TITLE
Documentation:  Using Comment blocks in functions

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#71]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

It could be advantageous for developers to have commented blocks of code for future developers making updates.  These comment blocks could point out salient features of the code and/or give a more detailed explanation of how the code works/processes.  This would be seen by developers  or by users inspecting the code on github.

We would like to establish a common way to use these comment blocks in our code.  

DoD:
Programming strategy has recommended best practice for using comments blocks in code.

@sgorm123 Does this capture our discussion yesterday?

**Comment by bundfussr** [comment]
@bms63 , @sgorm123 , I am not sure what you have discussed. I have added a "Comments" section in the programming strategy (see linked PR).
Could you have a look?

**Comment by bundfussr** [comment]
@bms63 , should we remove the "release Q4" label? Or do you think we have an agreement until next week?

**Comment by bundfussr** [comment]
Maybe, let's try.
