### ISSUE TITLE
Documentation:  Examples of when to use Default and Permitted Values

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#72]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

A good part of our function documentation have default and permitted values listed in the function arguments.  However, this is not completely adopted  across `admiral`.  

To remedy this:

- [ ] Update the Programming Strategy to have best practices on when and how Default to be used.
- [ ] Update the Programming Strategy to have best practices on when and how Permitted Values are to be used.
- [ ] #166
- [ ] Update function documentation for Default per programming strategy 
- [ ] Update function documentation for Permitted Values per programming strategy

**Comment by zdz2101** [comment]
Created a table of functions in admiral (43 impacted) which has at least 1 argument/param that contains the following in the roxygen block: 
`*Default*`
`*Permitted Values*`

[functions_to_check.csv](https://github.com/pharmaverse/admiraldev/files/9941730/functions_to_check.csv)

Table contains 4 columns: 
- the file that contains the function
- the function in question
- logical for if it contains default
- logical for if it contains permitted

**Comment by bms63** [comment]
omg @zdz2101 thank you for taking this on!!!

**Comment by bms63** [comment]
@zdz2101 can you break this into separate issues:

1) Clean up functions in admiral and admiraldev based on guidance developed in programming strategy (contingent on  updates from Adam)
2) Create the guidance itself in the programming strategy
