### ISSUE TITLE
Documentation: Update PR link templates

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#74]
@rossfarrugia There still seem to be some outdated links pointing to vignettes which now live in {admiraldev}.

![image](https://user-images.githubusercontent.com/11788080/188822642-ee42b34f-2740-44f2-9bf8-15a6854f2c25.png)

_Originally posted by @thomas-neitmann in https://github.com/pharmaverse/admiraldev/issues/69#issuecomment-1239041907_

**Comment by bms63** [comment]
I actually think this might be done, but it would be good to double check.

**Comment by bundfussr** [comment]
I have fixed them in https://github.com/pharmaverse/admiraldev/pull/78.

**Comment by PoojaKumari05** [comment]
@bms63  @bundfussr Should the issue be closed then?

**Comment by rossfarrugia** [comment]
@PoojaKumari05  no, we only close these issues at time of a release. for now the PR is open and needs review and once it merges it will go into `devel`, and then we move the issue to done on the project board, but we leave issues open for transparency for users until the release. Using the "closes #<issue_number>" convention in the PR titles auto-closes them once we merge to `main`.

**Comment by PoojaKumari05** [comment]
> @PoojaKumari05 no, we only close these issues at time of a release. for now the PR is open and needs review and once it merges it will go into `devel`, and then we move the issue to done on the project board, but we leave issues open for transparency for users until the release. Using the "closes #<issue_number>" convention in the PR titles auto-closes them once we merge to `main`.

Great - thanks @rossfarrugia for the details. :)

**Comment by esimms999-gsk** [comment]
I assigned @bundfussr since he says he has already fixed this. That way it will not show up as an unassigned "release Q4-2022" issue.
