### ISSUE TITLE
Documentation:  How to create an admiral function

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiraldev#75]
### Please select a category the issue is focused on?

Vignette

### Let us know where something needs a refresh or put your idea here!

goal: vignette that explains how to create a new admiral function

explain how to build a function with these in mind - **link to manifesto, other vignettes, programming strategy, style guide?**
**Part 1**
- [ ] readability
- [ ] findability 
- [ ] simplicity principles
**Part 2**
- [ ] technical: quoting and unquoting - how to use tidy within functions (i.e. !! vs. !!!) - **Thomas**

- [ ] example: building blocks

Pick some existing functions to explain decisions why things were done this way and not other, e.g. **generic functions vs specific functions**. - is it needed?

**Comment by bms63** [comment]
Closing as I think our admiral functions serve as good examples of how to write an admiral function
