### ISSUE TITLE
General Issue: Define scope of the package

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#8]
### Background Information

Current language in the Description File:
* A toolbox for developers working on pharmaverse admiral packages.

Current language in the README:
* Tools for developing functions and maintaining a healthy codebase within the family of admiral R packages.

But want to make sure we are all on the same page as these two phrases aren't exact and the overlap of `admiral` and `admiraldev` is a bit tricky. 

I see this package as not only being for a place for specific functions that help our `admiral` packages functions, but also give us reports and tools to make our development life easier.

For example, the testing Addin that reformats the testthat files to adhere to our Unit Test Guidance.  An addin that allows for easier setup of roxygen headers and reports on keywords and families being used.  I see a lot more potential here, but don't want it to get too wild!

### Definition of Done

The Scope of package is decided upon and written into the Readme.

**Comment by thomas-neitmann** [comment]
I'd change wording slightly to "A toolbox for developers working on {admiral} and its extension packages". Otherwise I like it 👍

**Comment by bms63** [comment]
> I think we should add more details for contributors and developers who want to add a new function. Which functions should be added to admiraldev and which to admiral?

I'm seeing an `admiral` function as something that adds a variable to a dataset or "helps" to add a variable to a dataset.  A helper could be a compute function, a source object, `get_` something, etc.  But we should define them clearly.  

While a function that checks the integrity of the function inputs and outputs is placed into `admiraldev`.   Hence the `assert` , `is and some of the `get` functions moving here.   I think `admiraldev`  scope should have some additional room for helper tools like the expect_dfs, dataset_vignette, addin for roxygen template and re-numberings tests, etc.

**Comment by bms63** [comment]
@rossfarrugia any thoughts on this?  also anyone else we should invite to this package.  I just added Robin, but wasn't sure if any onco or other core people should be included.  

@SyedMubasheer and @PoojaKumari05 just keeping you in the loop.

**Comment by rossfarrugia** [comment]
@bms63 my feeling is just start off with moving the pieces over that users don't ever need to use themselves from admiral (e.g. dev utility functions like the assertions) and then over time we could consider if anything else should move. if a user needs to use it directly though, I'd say leave it in admiral. I agree with your point that we'll add anything here over time that makes our development lives easier too.

On this note, one piece to consider including here from the start for me would be the CI/CD workflows as discussed at https://github.com/pharmaverse/admiraltemplate/pull/27 from admiraltemplate. It would cut down need for an extra new repo like {admiralci}.

**Comment by rossfarrugia** [comment]
also i'm fine with who you added from Roche side to this repo (I just removed Ondrej as he no longer works on this). we can add others over time as needed.

**Comment by bundfussr** [comment]
I am not sure if we should place the general workflows into admiraldev. If we do so, we can not modify them for admiraldev specific purposes because it would change the workflows for all other admiral related packages. Maybe it is safer to keep them separate.

**Comment by rossfarrugia** [comment]
@cicdguy (did you change your handle Dinakar? 😆 ) - note we decided at admiral core team that the CI/CD workflows should live in a new repo {admiralci} which you and your team could set-up and we could move all of https://github.com/pharmaverse/admiraltemplate/tree/main/.github/workflows (including the README) over to this repo. This means all other admiral repos then could just decide which workflows to assign based on the yaml approach and they would only ever be centrally maintained in one place. Sound ok to you?

**Comment by cicdguy** [comment]
> @cicdguy (did you change your handle Dinakar? 😆 ) 

Ha, yeah I did 😸 

> Sound ok to you?

That sounds great! We will begin migration when the repo is ready. Just make me an admin on that repo and we'll handle the rest.

**Comment by rossfarrugia** [comment]
Here goes:  https://github.com/pharmaverse/admiralci
