### ISSUE TITLE
Documentation:  Create a Standardized Roxygen Template for Developer Vignette

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#80]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

It has been observed that our roxygen headers are not standardized across the admiral code-base.  For example, some function headers have @author or @return in different places from other function headers.

In order to standardized all of our headers, we first need to create a Standard Template that shows the order of the tags and what should go in each tag.  This template will live in the[ Developer Guide-Programming Strategy](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#function-header-documentation) .  An existing example and guidance already exists and can be updated once agreed upon structure is met.

- Standardizing the headers also means a consistent structure across the Reference Tab on the packagedown site.
- This might be good as a check in the PR checklist that the roxygen headers follow the standard template?

Proposed Structure (Updated based on Stefan's feedback)

```
#' Title
#'
#' Short Description (If the description consists of more than one paragraph, use the `@description` tag.)
#'
#' @param dataset Descriptive Text (order of @param tags should be order as they appear in function)
#'
.
.
#' @param an_input Descriptive Text
#'
#' @details (Deep dive of purpose, recommend workflow, documentation/links)
#'
#' @return (What is returned by this function)
#'
#' @author (original and updating authors)
#'
#' @family (This will create an additional See Also section that links to similar functions)
#'
#' @keywords (This is helpful for our packagedown site to organize the reference page)
#'  If possible, use keywords which are used in `_pgkdown.yml`.
#'  If a new keyword is required, a corresponding section needs to be added to `_pgkdown.yml`.
#'  All keywords must be lower case.
#'
#' @seealso [related_function()] (This tag is optional. It should be used to refer to related functions.)
#'
#' @export
#'
#' @examples (Use `library(pkg_name)` rather than `pgk_name::function()`)
```

**Comment by esimms999-gsk** [comment]
Need some mention that we do not want importFrom in the roxygen header but, rather, in admiral-project.R.

**Comment by bms63** [comment]
Is this sufficient? https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#r-package-dependencies

**Comment by bundfussr** [comment]
@bms63 , should this be implemented for the upcoming release? Have we agreed on the template in the description?

We have a separate issue for the addin (https://github.com/pharmaverse/admiraldev/issues/11). Thus I think this issue need to cover the update of the programming strategy only.

**Comment by bms63** [comment]
I think the default and permitted values were outstanding questions.  I feel like there were a few more???

**Comment by bundfussr** [comment]
Should we remove the release Q4 label then? I don't think we find a solution for default and permitted values until next week.

**Comment by bms63** [comment]
yes i will remove it
