### ISSUE TITLE
Documentation:  Provide guidance for patches on using @devel

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#81]
### Let us know where something needs a refresh or put your idea here!

For pathces we should not use `@devel` on our branches.  This is not documented in our release strategy and we should update.  

https://pharmaverse.github.io/admiraldev/main/articles/git_usage.html#hot-fix-release

**Comment by zdz2101** [comment]
This one may also already be taken care of by #112 with the cross-reference link to Hot Fix Release. @bms63 @rossfarrugia

**Comment by bms63** [comment]
I don't think it is covered in that vignette https://pharmaverse.github.io/admiraldev/devel/articles/release_strategy.html

**Comment by zdz2101** [comment]
From line 30 of git_usage.Rmd: 
`
- The `patch` branch is reserved for special hot fixes to address bugs. More info in [Hot Fix Release](release_strategy.html#hot-fix-release)
`

Then from line 59 of release_strategy.Rmd:

`
1) Branches addressing the bugs should have Pull Requests merged into the `patch` branch **NOT** the `devel` branch.
`

Is this cross-reference not sufficient? Or does it need to be noted also in git_usage.Rmd?

**Comment by bms63** [comment]
Oh this is for using the suffix at the end of the branch name `@devel`

**Comment by rossfarrugia** [comment]
@bms63 what should we use instead `@main` or just no suffix? sorry, i don't remember the background on this issue

**Comment by thomas-neitmann** [comment]
Yes, it should be `@main`.
