### ISSUE TITLE
General Issue:  What are we reexporting and why

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#83]
### Background Information

In admiral, We reexport some functions.  We should document why we do this in one of our dev vignettes

![image](https://user-images.githubusercontent.com/10111024/189975876-7b90cfb3-390d-4a43-bba6-3ac79982b19f.png)

### Definition of Done

Explanation of when you might need to re-export functions in a package

**Comment by bundfussr** [comment]
I wonder why we reexport functions from admiraldev. If they are user-facing, they should be in admiral and not in admiraldev. If they are not user-facing, there is no need to export them.

@bms63 , @thomas-neitmann , what do you think?

**Comment by bms63** [comment]
I think I made a mistake in bringing them over - so we should probably just keep these three functions in admiral if they are only user-facing functions.

**Comment by bundfussr** [comment]
`negate_vars()` is used in the templates. So we should bring it back to admiral.

I am not sure about `filter_if()` and `vars2chr()`.

**Comment by bms63** [comment]
# For `filter_if` 

using `grep -r3 "filter_if" > filter_if.txt` I only seeing it being used internally in functions.  Probably safe to move to `admiraldev`


man/reexports.Rd-\docType{import}
man/reexports.Rd-\name{reexports}
man/reexports.Rd-\alias{reexports}
man/reexports.Rd:\alias{filter_if}
man/reexports.Rd-\alias{negate_vars}
man/reexports.Rd-\alias{vars2chr}
man/reexports.Rd-\alias{vars}
--
man/reexports.Rd-below to see their documentation.
man/reexports.Rd-
man/reexports.Rd-\describe{
man/reexports.Rd:  \item{admiraldev}{\code{\link[admiraldev]{filter_if}}, \code{\link[admiraldev]{negate_vars}}, \code{\link[admiraldev]{vars2chr}}}
man/reexports.Rd-
man/reexports.Rd-  \item{dplyr}{\code{\link[dplyr]{desc}}, \code{\link[dplyr]{vars}}}
man/reexports.Rd-}}
--
tests/testthat/test-utils.R-
tests/testthat/test-utils.R-  expect_dfs_equal(
tests/testthat/test-utils.R-    input,
tests/testthat/test-utils.R:    filter_if(input, quo(NULL)),
tests/testthat/test-utils.R-    keys = c("USUBJID", "VSTESTCD")
tests/testthat/test-utils.R-  )
tests/testthat/test-utils.R-})
--
tests/testthat/test-utils.R-
tests/testthat/test-utils.R-  expect_dfs_equal(
tests/testthat/test-utils.R-    input[1L, ],
tests/testthat/test-utils.R:    filter_if(input, quo(VSTESTCD == "WEIGHT")),
tests/testthat/test-utils.R-    keys = c("USUBJID", "VSTESTCD")
tests/testthat/test-utils.R-  )
tests/testthat/test-utils.R-})
--
NAMESPACE-export(filter_confirmation)
NAMESPACE-export(filter_date_sources)
NAMESPACE-export(filter_extreme)
NAMESPACE:export(filter_if)
NAMESPACE-export(filter_relative)
NAMESPACE-export(format_eoxxstt_default)
NAMESPACE-export(format_reason_default)
Binary file .git/objects/pack/pack-5a393da68764f870bf00efef5c443abfd96ac226.pack matches
--
R/get_summary_records.R-  # Summarise the analysis value
R/get_summary_records.R-  dataset %>%
R/get_summary_records.R-    group_by(!!!by_vars) %>%
R/get_summary_records.R:    filter_if(filter) %>%
R/get_summary_records.R-    summarise(!!analysis_var := summary_fun(!!analysis_var)) %>%
R/get_summary_records.R-    mutate(!!!set_values_to) %>%
R/get_summary_records.R-    ungroup()
--
R/derive_var_dthcaus.R-    source_dataset_name <- sources[[ii]]$dataset_name
R/derive_var_dthcaus.R-    source_dataset <- source_datasets[[source_dataset_name]]
R/derive_var_dthcaus.R-    add_data[[ii]] <- source_dataset %>%
R/derive_var_dthcaus.R:      filter_if(sources[[ii]]$filter)
R/derive_var_dthcaus.R-
R/derive_var_dthcaus.R-    assert_date_var(
R/derive_var_dthcaus.R-      dataset = add_data[[ii]],
--
R/derive_param_exposure.R-  assert_s3_class(summary_fun, "function")
R/derive_param_exposure.R-
R/derive_param_exposure.R-  subset_ds <- dataset %>%
R/derive_param_exposure.R:    filter_if(filter)
R/derive_param_exposure.R-
R/derive_param_exposure.R-  add_data <- subset_ds %>%
R/derive_param_exposure.R-    get_summary_records(
--
R/derive_var_extreme_date.R-      dataset_name = source_dataset_name
R/derive_var_extreme_date.R-    )
R/derive_var_extreme_date.R-    add_data[[i]] <- source_dataset %>%
R/derive_var_extreme_date.R:      filter_if(sources[[i]]$filter) %>%
R/derive_var_extreme_date.R-      filter_extreme(
R/derive_var_extreme_date.R-        order = vars(!!date),
R/derive_var_extreme_date.R-        by_vars = subject_keys,
--
R/derive_vars_transposed.R-  assert_data_frame(dataset_merge, required_vars = quo_c(by_vars, key_var, value_var))
R/derive_vars_transposed.R-
R/derive_vars_transposed.R-  dataset_transposed <- dataset_merge %>%
R/derive_vars_transposed.R:    filter_if(filter) %>%
R/derive_vars_transposed.R-    pivot_wider(names_from = !!key_var, values_from = !!value_var)
R/derive_vars_transposed.R-
R/derive_vars_transposed.R-  left_join(dataset, dataset_transposed, by = vars2chr(by_vars))
--
R/assertions.R:filter_if <- function(dataset, filter) {
R/assertions.R-  assert_data_frame(dataset, check_is_grouped = FALSE)
R/assertions.R-  assert_filter_cond(filter, optional = TRUE)
R/assertions.R-  if (quo_is_null(filter)) {
--
R/derive_param_tte.R-      dataset_name = sources[[i]]$dataset_name
R/derive_param_tte.R-    )
R/derive_param_tte.R-    data[[i]] <- source_dataset %>%
R/derive_param_tte.R:      filter_if(sources[[i]]$filter) %>%
R/derive_param_tte.R-      filter_extreme(
R/derive_param_tte.R-        order = vars(!!date),
R/derive_param_tte.R-        by_vars = quo_c(subject_keys, by_vars),
--
R/derive_extreme_records.R-
R/derive_extreme_records.R-  # Create new observations
R/derive_extreme_records.R-  new_obs <- dataset %>%
R/derive_extreme_records.R:    filter_if(filter) %>%
R/derive_extreme_records.R-    filter_extreme(
R/derive_extreme_records.R-      by_vars = by_vars,
R/derive_extreme_records.R-      order = order,
--
R/derive_param_computed.R-
R/derive_param_computed.R-  # select observations and variables required for new observations
R/derive_param_computed.R-  data_filtered <- dataset %>%
R/derive_param_computed.R:    filter_if(filter)
R/derive_param_computed.R-
R/derive_param_computed.R-  data_parameters <- data_filtered %>%
R/derive_param_computed.R-    filter(PARAMCD %in% parameters)
--
R/reexports.R-#' @export
R/reexports.R:admiraldev::filter_if
R/reexports.R-
R/reexports.R-#' @export
R/reexports.R-admiraldev::negate_vars
--
R/derive_vars_last_dose.R-  # filter EX based on user-specified condition
R/derive_vars_last_dose.R-  if (!is.null(quo_get_expr(filter_ex))) {
R/derive_vars_last_dose.R-    dataset_ex <- dataset_ex %>%
R/derive_vars_last_dose.R:      filter_if(filter_ex)
R/derive_vars_last_dose.R-  }
R/derive_vars_last_dose.R-
R/derive_vars_last_dose.R-  # create traceability vars if requested
--
R/derive_param_first_event.R-  adsl_vars <- colnames(dataset_adsl)
R/derive_param_first_event.R-
R/derive_param_first_event.R-  events <- dataset_source %>%
R/derive_param_first_event.R:    filter_if(filter_source) %>%
R/derive_param_first_event.R-    filter_extreme(
R/derive_param_first_event.R-      by_vars = subject_keys,
R/derive_param_first_event.R-      order = vars(!!date_var),
--
R/derive_merged.R-  assert_data_frame(dataset_add, required_vars = quo_c(by_vars, extract_vars(order), new_vars))
R/derive_merged.R-  match_flag <- assert_symbol(enquo(match_flag), optional = TRUE)
R/derive_merged.R-
R/derive_merged.R:  add_data <- filter_if(dataset_add, filter_add)
R/derive_merged.R-  if (!is.null(order)) {
R/derive_merged.R-    add_data <- filter_extreme(
R/derive_merged.R-      add_data,
--
R/derive_merged.R-  } else {
R/derive_merged.R-    highest_imputation <- "M"
R/derive_merged.R-  }
R/derive_merged.R:  add_data <- filter_if(dataset_add, filter_add) %>%
R/derive_merged.R-    derive_vars_dt(
R/derive_merged.R-      new_vars_prefix = new_vars_prefix,
R/derive_merged.R-      dtc = !!dtc,
--
R/derive_merged.R-    highest_imputation <- "n"
R/derive_merged.R-    time_imputation <- "first"
R/derive_merged.R-  }
R/derive_merged.R:  add_data <- filter_if(dataset_add, filter = filter_add) %>%
R/derive_merged.R-    derive_vars_dtm(
R/derive_merged.R-      new_vars_prefix = new_vars_prefix,
R/derive_merged.R-      dtc = !!dtc,
--
R/derive_merged.R-  filter_add <- assert_filter_cond(enquo(filter_add), optional = TRUE)
R/derive_merged.R-  assert_data_frame(dataset_add, required_vars = quo_c(by_vars, source_var))
R/derive_merged.R-
R/derive_merged.R:  add_data <- filter_if(dataset_add, filter_add) %>%
R/derive_merged.R-    mutate(!!new_var := cat_fun(!!source_var))
R/derive_merged.R-  derive_vars_merged(
R/derive_merged.R-    dataset,
--
R/derive_merged.R-  filter_add <-
R/derive_merged.R-    assert_filter_cond(enquo(filter_add), optional = TRUE)
R/derive_merged.R-
R/derive_merged.R:  add_data <- filter_if(dataset_add, filter_add) %>%
R/derive_merged.R-    mutate(!!new_var := if_else(!!condition, 1, 0, 0))
R/derive_merged.R-
R/derive_merged.R-  derive_vars_merged(
--
R/derive_merged.R-  } else if (case == "title") {
R/derive_merged.R-    trans <- expr(str_to_title(!!source_var))
R/derive_merged.R-  }
R/derive_merged.R:  add_data <- filter_if(dataset_add, filter_add) %>%
R/derive_merged.R-    mutate(!!new_var := !!trans)
R/derive_merged.R-  derive_vars_merged(
R/derive_merged.R-    dataset,
--

# For `vars2chr` 

grep -r3 "vars2chr" > vars2chr.txt.  This one might have some documentation using it, but mostly used within function code.


filter_if.txt-man/reexports.Rd-\alias{reexports}
filter_if.txt-man/reexports.Rd:\alias{filter_if}
filter_if.txt-man/reexports.Rd-\alias{negate_vars}
filter_if.txt:man/reexports.Rd-\alias{vars2chr}
filter_if.txt-man/reexports.Rd-\alias{vars}
filter_if.txt---
filter_if.txt-man/reexports.Rd-below to see their documentation.
filter_if.txt-man/reexports.Rd-
filter_if.txt-man/reexports.Rd-\describe{
filter_if.txt:man/reexports.Rd:  \item{admiraldev}{\code{\link[admiraldev]{filter_if}}, \code{\link[admiraldev]{negate_vars}}, \code{\link[admiraldev]{vars2chr}}}
filter_if.txt-man/reexports.Rd-
filter_if.txt-man/reexports.Rd-  \item{dplyr}{\code{\link[dplyr]{desc}}, \code{\link[dplyr]{vars}}}
filter_if.txt-man/reexports.Rd-}}
--
filter_if.txt-R/derive_vars_transposed.R:    filter_if(filter) %>%
filter_if.txt-R/derive_vars_transposed.R-    pivot_wider(names_from = !!key_var, values_from = !!value_var)
filter_if.txt-R/derive_vars_transposed.R-
filter_if.txt:R/derive_vars_transposed.R-  left_join(dataset, dataset_transposed, by = vars2chr(by_vars))
filter_if.txt---
filter_if.txt-R/assertions.R:filter_if <- function(dataset, filter) {
filter_if.txt-R/assertions.R-  assert_data_frame(dataset, check_is_grouped = FALSE)
--
man/derive_vars_merged_dt.Rd-\emph{Default}:
man/derive_vars_merged_dt.Rd-
man/derive_vars_merged_dt.Rd-\if{html}{\out{<div class="sourceCode r">}}\preformatted{paste("Dataset `dataset_add` contains duplicate records with respect to",
man/derive_vars_merged_dt.Rd:      enumerate(vars2chr(by_vars)))
man/derive_vars_merged_dt.Rd-}\if{html}{\out{</div>}}}
man/derive_vars_merged_dt.Rd-}
man/derive_vars_merged_dt.Rd-\value{
--
man/derive_vars_merged_lookup.Rd-\emph{Default}:
man/derive_vars_merged_lookup.Rd-
man/derive_vars_merged_lookup.Rd-\if{html}{\out{<div class="sourceCode r">}}\preformatted{paste("Dataset `dataset_add` contains duplicate records with respect to",
man/derive_vars_merged_lookup.Rd:      enumerate(vars2chr(by_vars)))
man/derive_vars_merged_lookup.Rd-}\if{html}{\out{</div>}}}
man/derive_vars_merged_lookup.Rd-
man/derive_vars_merged_lookup.Rd-\item{print_not_mapped}{Print a list of unique \code{by_vars} values that do not
--
man/derive_vars_merged_dtm.Rd-\emph{Default}:
man/derive_vars_merged_dtm.Rd-
man/derive_vars_merged_dtm.Rd-\if{html}{\out{<div class="sourceCode r">}}\preformatted{paste("Dataset `dataset_add` contains duplicate records with respect to",
man/derive_vars_merged_dtm.Rd:      enumerate(vars2chr(by_vars)))
man/derive_vars_merged_dtm.Rd-}\if{html}{\out{</div>}}}
man/derive_vars_merged_dtm.Rd-}
man/derive_vars_merged_dtm.Rd-\value{
--
man/signal_duplicate_records.Rd-  dataset,
man/signal_duplicate_records.Rd-  by_vars,
man/signal_duplicate_records.Rd-  msg = paste("Dataset contains duplicate records with respect to",
man/signal_duplicate_records.Rd:    enumerate(vars2chr(by_vars))),
man/signal_duplicate_records.Rd-  cnd_type = "error"
man/signal_duplicate_records.Rd-)
man/signal_duplicate_records.Rd-}
--
man/reexports.Rd-\alias{reexports}
man/reexports.Rd-\alias{filter_if}
man/reexports.Rd-\alias{negate_vars}
man/reexports.Rd:\alias{vars2chr}
man/reexports.Rd-\alias{vars}
man/reexports.Rd-\alias{desc}
man/reexports.Rd-\title{Objects exported from other packages}
--
man/reexports.Rd-below to see their documentation.
man/reexports.Rd-
man/reexports.Rd-\describe{
man/reexports.Rd:  \item{admiraldev}{\code{\link[admiraldev]{filter_if}}, \code{\link[admiraldev]{negate_vars}}, \code{\link[admiraldev]{vars2chr}}}
man/reexports.Rd-
man/reexports.Rd-  \item{dplyr}{\code{\link[dplyr]{desc}}, \code{\link[dplyr]{vars}}}
man/reexports.Rd-}}
--
man/derive_vars_merged.Rd-\emph{Default}:
man/derive_vars_merged.Rd-
man/derive_vars_merged.Rd-\if{html}{\out{<div class="sourceCode r">}}\preformatted{paste("Dataset `dataset_add` contains duplicate records with respect to",
man/derive_vars_merged.Rd:      enumerate(vars2chr(by_vars)))
man/derive_vars_merged.Rd-}\if{html}{\out{</div>}}}
man/derive_vars_merged.Rd-}
man/derive_vars_merged.Rd-\value{
--
R/derive_vars_dtm_to_tm.R-
R/derive_vars_dtm_to_tm.R-  # Warn if `--TM` variables already exist
R/derive_vars_dtm_to_tm.R-  dtm_vars <- quo_c(source_vars)
R/derive_vars_dtm_to_tm.R:  dtm_vars2 <- vars2chr(dtm_vars)
R/derive_vars_dtm_to_tm.R-  n_vars <- length(dtm_vars)
R/derive_vars_dtm_to_tm.R-
R/derive_vars_dtm_to_tm.R-  for (i in n_vars) {
--
R/derive_var_extreme_date.R-    )
R/derive_var_extreme_date.R-  )
R/derive_var_extreme_date.R-
R/derive_var_extreme_date.R:  warn_if_vars_exist(dataset, vars2chr(quo_c(new_var)))
R/derive_var_extreme_date.R-
R/derive_var_extreme_date.R-  add_data <- vector("list", length(sources))
R/derive_var_extreme_date.R-  for (i in seq_along(sources)) {
--
R/derive_vars_transposed.R-    filter_if(filter) %>%
R/derive_vars_transposed.R-    pivot_wider(names_from = !!key_var, values_from = !!value_var)
R/derive_vars_transposed.R-
R/derive_vars_transposed.R:  left_join(dataset, dataset_transposed, by = vars2chr(by_vars))
R/derive_vars_transposed.R-}
R/derive_vars_transposed.R-
R/derive_vars_transposed.R-#' Derive ATC Class Variables
--
R/derive_param_tte.R-      assert_one_to_one(new_param, vars(PARAMCD), by_vars)
R/derive_param_tte.R-    }
R/derive_param_tte.R-
R/derive_param_tte.R:    # -vars2chr(by_vars) does not work for 3.5 #
R/derive_param_tte.R-    new_param <- select(new_param, !!!negate_vars(by_vars))
R/derive_param_tte.R-  }
R/derive_param_tte.R-
--
R/derive_param_tte.R-  assert_list_of(source_datasets, "data.frame")
R/derive_param_tte.R-  assert_vars(by_vars)
R/derive_param_tte.R-  # ensure that the by variables are contained in all source datasets #
R/derive_param_tte.R:  by_vars_chr <- vars2chr(by_vars)
R/derive_param_tte.R-  # determine which source datasets need to be extended #
R/derive_param_tte.R-  by_groups <- list()
R/derive_param_tte.R-  extend <- vector("list", length(source_datasets))
--
R/derive_param_computed.R-    by_vars = vars(!!!by_vars, PARAMCD),
R/derive_param_computed.R-    msg = paste(
R/derive_param_computed.R-      "The filtered input dataset contains duplicate records with respect to",
R/derive_param_computed.R:      enumerate(c(vars2chr(by_vars), "PARAMCD")),
R/derive_param_computed.R-      "\nPlease ensure that the variables specified for `by_vars` and `PARAMCD`",
R/derive_param_computed.R-      "are a unique key of the input data set restricted by the condition",
R/derive_param_computed.R-      "specified for `filter` and to the parameters specified for `parameters`."
--
R/derive_param_computed.R-    hori_const_data <- data_const_parameters %>%
R/derive_param_computed.R-      pivot_wider(names_from = PARAMCD, values_from = AVAL, names_prefix = "AVAL.")
R/derive_param_computed.R-
R/derive_param_computed.R:    hori_data <- inner_join(hori_data, hori_const_data, by = vars2chr(constant_by_vars))
R/derive_param_computed.R-  }
R/derive_param_computed.R-
R/derive_param_computed.R-  # add analysis value (AVAL) and parameter variables, e.g., PARAMCD
--
R/derive_vars_dtm_to_dt.R-
R/derive_vars_dtm_to_dt.R-  # Warn if `--TM` variables already exist
R/derive_vars_dtm_to_dt.R-  dtm_vars <- quo_c(source_vars)
R/derive_vars_dtm_to_dt.R:  dtm_vars2 <- vars2chr(dtm_vars)
R/derive_vars_dtm_to_dt.R-  n_vars <- length(dtm_vars)
R/derive_vars_dtm_to_dt.R-
R/derive_vars_dtm_to_dt.R-  for (i in n_vars) {
--
R/filter_extreme.R-  # group and sort input dataset
R/filter_extreme.R-  tmp_obs_nr <- get_new_tmp_var(dataset)
R/filter_extreme.R-  if (!is.null(by_vars)) {
R/filter_extreme.R:    assert_has_variables(dataset, vars2chr(by_vars))
R/filter_extreme.R-
R/filter_extreme.R-    data <- dataset %>%
R/filter_extreme.R-      derive_var_obs_number(
--
R/derive_vars_dy.R-  n_vars <- length(source_vars)
R/derive_vars_dy.R-  source_names <- names(source_vars)
R/derive_vars_dy.R-
R/derive_vars_dy.R:  bad_vars <- vars2chr(source_vars)[(
R/derive_vars_dy.R:    (source_names == "" | source_names == vars2chr(source_vars)) &
R/derive_vars_dy.R:      !str_detect(vars2chr(source_vars), "(DT|DTM)$"))]
R/derive_vars_dy.R-
R/derive_vars_dy.R-  if (length(bad_vars > 0)) {
R/derive_vars_dy.R-    err_msg <-
--
R/derive_vars_dy.R-
R/derive_vars_dy.R-  dy_vars <- if_else(
R/derive_vars_dy.R-    source_names == "",
R/derive_vars_dy.R:    stringr::str_replace_all(vars2chr(source_vars), "(DT|DTM)$", "DY"),
R/derive_vars_dy.R-    source_names
R/derive_vars_dy.R-  )
R/derive_vars_dy.R-  warn_if_vars_exist(dataset, dy_vars)
--
R/filter_confirmation.R-    left_join(
R/filter_confirmation.R-      data,
R/filter_confirmation.R-      select(data, !!!by_vars, !!!join_vars, tmp_obs_nr_filter_confirmation),
R/filter_confirmation.R:      by = vars2chr(by_vars),
R/filter_confirmation.R-      suffix = c("", ".join")
R/filter_confirmation.R-    )
R/filter_confirmation.R-  if (join_type != "all") {
--
R/reexports.R-admiraldev::negate_vars
R/reexports.R-
R/reexports.R-#' @export
R/reexports.R:admiraldev::vars2chr
R/reexports.R-
R/reexports.R-#' @export
R/reexports.R-dplyr::vars
--
R/derive_vars_last_dose.R-  )
R/derive_vars_last_dose.R-
R/derive_vars_last_dose.R-  # vars converted to string
R/derive_vars_last_dose.R:  by_vars_str <- vars2chr(by_vars)
R/derive_vars_last_dose.R:  dose_id_str <- vars2chr(dose_id)
R/derive_vars_last_dose.R-
R/derive_vars_last_dose.R-  # check if single_dose_condition is true for all EX records
R/derive_vars_last_dose.R-  single_dose_eval <- dataset_ex %>%
--
R/derive_var_base.R-    by_vars = by_vars,
R/derive_var_base.R-    duplicate_msg = paste(
R/derive_var_base.R-      "Input dataset contains multiple baseline records with respect to",
R/derive_var_base.R:      enumerate(vars2chr(by_vars))
R/derive_var_base.R-    )
R/derive_var_base.R-  )
R/derive_var_base.R-}
--
R/duplicates.R-#' signal_duplicate_records(adsl, vars(USUBJID), cnd_type = "message")
R/duplicates.R-signal_duplicate_records <- function(dataset,
R/duplicates.R-                                     by_vars,
R/duplicates.R:                                     msg = paste("Dataset contains duplicate records with respect to", enumerate(vars2chr(by_vars))), # nolint
R/duplicates.R-                                     cnd_type = "error") {
R/duplicates.R-  assert_vars(by_vars)
R/duplicates.R-  assert_data_frame(dataset, required_vars = by_vars, check_is_grouped = FALSE)
--
R/duplicates.R-    .datasets$duplicates <- structure(
R/duplicates.R-      duplicate_records,
R/duplicates.R-      class = union("duplicates", class(duplicate_records)),
R/duplicates.R:      by_vars = vars2chr(by_vars)
R/duplicates.R-    )
R/duplicates.R-    full_msg <- paste0(msg, "\nRun `get_duplicates_dataset()` to access the duplicate records")
R/duplicates.R-    cnd_funs[[cnd_type]](full_msg)
--
R/derive_param_wbc_abs.R-  assert_character_scalar(diff_type, values = c("percent", "fraction"))
R/derive_param_wbc_abs.R-  get_unit_expr <- assert_expr(enquo(get_unit_expr))
R/derive_param_wbc_abs.R-  assert_character_scalar(wbc_unit)
R/derive_param_wbc_abs.R:  by_vars_str <- vars2chr(by_vars)
R/derive_param_wbc_abs.R-
R/derive_param_wbc_abs.R-  # Check unit of input parameters
R/derive_param_wbc_abs.R-  assert_unit(dataset, wbc_code, required_unit = wbc_unit, get_unit_expr = !!get_unit_expr)
--
R/derive_merged.R-#'
R/derive_merged.R-#'   ```{r echo=TRUE, eval=FALSE}
R/derive_merged.R-#'   paste("Dataset `dataset_add` contains duplicate records with respect to",
R/derive_merged.R:#'         enumerate(vars2chr(by_vars)))
R/derive_merged.R-#'   ```
R/derive_merged.R-#'
R/derive_merged.R-#' @return The output dataset contains all observations and variables of the
--
R/derive_merged.R-    if (is.null(duplicate_msg)) {
R/derive_merged.R-      duplicate_msg <- paste(
R/derive_merged.R-        "Dataset `dataset_add` contains duplicate records with respect to",
R/derive_merged.R:        enumerate(vars2chr(by_vars))
R/derive_merged.R-      )
R/derive_merged.R-    }
R/derive_merged.R-    signal_duplicate_records(
--
R/derive_merged.R-  # check if there are any variables in both datasets which are not by vars
R/derive_merged.R-  # in this case an error is issued to avoid renaming of varibles by left_join()
R/derive_merged.R-  common_vars <-
R/derive_merged.R:    setdiff(intersect(names(dataset), names(add_data)), vars2chr(by_vars))
R/derive_merged.R-  if (length(common_vars) > 0L) {
R/derive_merged.R-    abort(if_else(
R/derive_merged.R-      length(common_vars) == 1L,
--
R/derive_merged.R-      )
R/derive_merged.R-    ))
R/derive_merged.R-  }
R/derive_merged.R:  left_join(dataset, add_data, by = vars2chr(by_vars))
R/derive_merged.R-}
R/derive_merged.R-
R/derive_merged.R-#' Merge a (Imputed) Date Variable
--
R/derive_merged.R-      .temp$nmap <- structure(
R/derive_merged.R-        temp_not_mapped,
R/derive_merged.R-        class = union("nmap", class(temp_not_mapped)),
R/derive_merged.R:        by_vars = vars2chr(by_vars)
R/derive_merged.R-      )
R/derive_merged.R-
R/derive_merged.R-      message(
R/derive_merged.R:        "List of ", enumerate(vars2chr(by_vars)), " not mapped: ", "\n",
R/derive_merged.R-        paste0(capture.output(temp_not_mapped), collapse = "\n"),
R/derive_merged.R-        "\nRun `get_not_mapped()` to access the full list"
R/derive_merged.R-      )
R/derive_merged.R-    } else if (nrow(temp_not_mapped) == 0) {
R/derive_merged.R-      message(
R/derive_merged.R:        "All ", enumerate(vars2chr(by_vars)), " are mapped."
R/derive_merged.R-      )
R/derive_merged.R-    }
R/derive_merged.R-  }
--

**Comment by bms63** [comment]
So maybe move `negate_vars` to admiral, keep `filter_if` in admiraldev.

For `vars2chr`, is there another way to write the documentation for the functions to not use it and then move to `admiraldev`, or just keep in `admiral` to make it easier on us and not have it in `admiraldev`.

**Comment by bundfussr** [comment]
Maybe we should keep `vars2chr()` in admiral. It could be useful for users which have a mix of admiral and non-admiral functions in their script:
```
param_by_vars <- vars(AVISIT, AVISITN)

adxx <- adxx %>%
  derive_param_map(by_vars = param_by_vars) %>%
  full_join(some_data, by = vars2chr(param_by_vars)
```

**Comment by bms63** [comment]
Did `dplyr` remove the warning messages around their join functions?  Let's check this out.

**Comment by thomas-neitmann** [comment]
Add a blurb in the "R Package Dependencies" section of the Programming Startegy.

**Comment by bundfussr** [comment]
I think the definition of what should be reexported is a bit to broad. Maybe we should be a bit more restrictive like: "This applies to functions which are frequently called within admiral function calls like `vars()` or `desc()`." Then it is clearer that we do not want to reexport functions like `tribble()` or `select()`.

However, I wonder if we should remove `reexports.R` completely. Currently we reexport three functions from admiraldev and two from dplyr. I think we should never reexport functions from admiraldev because if they are user-facing, they should be in admiral and not in admiraldev. It makes sense to reexport `vars()` and `desc()` from dplyr because these are required for many admiral function calls. On the other side, it is unlikely that somebody uses admiral but not dplyr. So I am not sure if there is a benefit for the users.

**Comment by bms63** [comment]
`dplyr` is a strict dependency for `admiral` so a user would always have it in their library.  I'm still not entirely clear on why we re-export `vars()` and `desc()`  if dplyr is already loaded.  

It would be great if we could get rid of `reexports.R`

Agree that functions in admiraldev should be re-exported.  Let's make a call on where they live.  I think we ran out of time last release and ended up with having to re-export a few functions to make everything work.

Maybe @zdz2101 this will morph into not a documentation issue and more of tying up loose programming ends.

**Comment by zdz2101** [comment]
I agree with the migration of the three admiraldev functions to admiral. 

In terms of the two `dplyr` functions, there is a border case where you can try running admiral without ever calling `library(dplyr)` and the reexport of `vars()` becomes critical. In fact, I think we would need to check all the roxygen examples that call `vars()` but **don't** have `library(dplyr)` called at the top If we choose to remove `reexports.R` entirely. I think this would become part of the task as well.

**Comment by zdz2101** [comment]
If we remove the reexport of the dplyr functions in admiraldev, does documentation still need to be written about eexports?

**Comment by bms63** [comment]
It does not need to be written.  Again a little nervous about this one!!  But we will see what happens
