### ISSUE TITLE
Documentation:  Update needed in Programming Strategy Vignette

### ISSUE THREAD

**Issue by sophie-gem** [pharmaverse/admiraldev#89]
### Please select a category the issue is focused on?

Developer Guides

### Let us know where something needs a refresh or put your idea here!

![image](https://user-images.githubusercontent.com/90790226/190224515-7c503d7e-058e-4575-8a11-a487b5ad7b0e.png)

In the `Deprecation: Documentation` section of the `Programming Strategy` vignette (circled in red on the above screenshot):
- The yellow highlighted line needs to be updated to "the `@family` tag will become `deprecated`"
- This then should be shown in the code block below the yellow highlight. Somewhere near the red asterisk needs to show the line `#' @family deprecated`

These changes are required to be consistent with current practices in {admiral}.

**Comment by sophie-gem** [comment]
I would be happy to pick this one up 😄

**Comment by thomas-neitmann** [comment]
We're counting on your help @sophie-gem!

**Comment by thomas-neitmann** [comment]
Fyi @bms63

**Comment by sophie-gem** [comment]
Hi @bms63, I was wondering if you'd be able to give me the right permissions to be able to push the branch up to the remote? It is currently telling me that permission to do so is denied.

![image](https://user-images.githubusercontent.com/90790226/192219080-f644fcbf-f8b8-4eae-8adc-9c78b44ddb77.png)

Many thanks!

**Comment by thomas-neitmann** [comment]
@sophie-gem While @bms63 is still asleep and went ahead and added you to admiraldev.

**Comment by sophie-gem** [comment]
Ah that's great, thanks @thomas-neitmann!
