### ISSUE TITLE
General Issue: Running list of functions to remove from admiral

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#9]
### Background Information

- [x] .rlang_as_friendly_type
- [x] .rlang_as_friendly_vector_type
- [x] .rlang_stop_unexpected_typeof
- [x] `%notin%` (keep in admiral) 
- [x] `%or%`
- [x] anti_join
- [x] arg_name
- [x] as_name
- [x] assert_character_scalar
- [x] assert_character_vector
- [x] assert_data_frame
- [x] assert_db_requirements (keep in admiral)
- [x] assert_expr
- [x] assert_filter_cond
- [x] assert_function
- [x] assert_function_param
- [x] assert_has_variables
- [x] assert_integer_scalar
- [x] assert_list_element
- [x] assert_list_of
- [x] assert_list_of_formulas (Removed from admiraldev and needs to be removed from admiral)
- [x] assert_logical_scalar
- [x] assert_named_exprs
- [x] assert_numeric_vector
- [x] assert_one_to_one
- [x] assert_order_vars
- [x] assert_param_does_not_exist
- [x] assert_s3_class
- [x] assert_symbol
- [x] assert_terms (keep in admiral - rename?)
- [x] assert_unit
- [x] assert_valid_queries
- [x] assert_vars
- [x] assert_varval_list
- [x] backquote
- [x] contains_vars
- [x] dataset_vignette
- [x] dquote
- [x] enumerate
- [x] expect_dfs_equal
- [x] extend_source_datasets (keep in admiral)
- [x] extract_vars
- [x] format.sdg_select (keep in admiral)
- [x] format.smq_select (keep in admiral)
- [x] format_arg
- [x] friendly_type_of
- [x] get_constant_vars
- [x] get_duplicates
- [x] get_source_vars
- [x] grapes-notin-grapes (not sure what this is?)
- [x] inner_join
- [x] is_auto
- [x] is_date
- [x] is_named
- [x] is_order_vars
- [x] is_timeunit
- [x] is_valid_date_entry
- [x] is_valid_day
- [x] is_valid_dtc
- [x] is_valid_hour
- [x] is_valid_month
- [x] is_valid_sec_min
- [x] is_valid_time_entry
- [x] left_join
- [x] print.duplicates (stay in admiral)
- [x] quo_c
- [x] quo_is_desc_call
- [x] quo_not_missing
- [x] replace_values_by_names
- [x] squote
- [x] stop_input_type
- [x] suppress_warning
- [x] valid_time_units
- [x] validate_query (keep in admiral)
- [x] validate_sdg_select (keep in admiral)
- [x] validate_smq_select (keep in admiral)
- [x] warn_if_incomplete_dtc
- [x] warn_if_inconsistent_list
- [x] warn_if_invalid_dtc
- [x] warn_if_vars_exist
- [x] what_is_it

### Definition of Done

- [ ]  Final list of functions created 
- [ ]  This list of functions and tests are removed from admiral

**Comment by thomas-neitmann** [comment]
In addition I'd move the following functions from `R/duplicates.R` to {admiraldev}:

- [ ] extract_duplicate_records
- [ ] signal_duplicate_records
- [ ] print.duplicates
- [ ] get_duplicates_dataset

**Comment by thomas-neitmann** [comment]
Plus `expect_dfs_equal()` from `R/test_helpers.R` and the `*_join()` functions from `R/joins.R`.

**Comment by bundfussr** [comment]
Are you sure we should move `get_duplicates_dataset()`? Usually it is called by users and not within a function.

**Comment by thomas-neitmann** [comment]
Good point. Maybe we should keep all of these duplicate related functions in {admiral} then? I feel like it would only lead to confusing having the signaling and retrieving of duplicates sit in two different packages.

**Comment by bundfussr** [comment]
Yes, I agree.

**Comment by bms63** [comment]
@thomas-neitmann @bundfussr I have a final list of all the functions that I think should be moved from `admiral` to `admiraldev`.  

This is most recent extraction of admiral functions keywords and families from the 1105-restructure branch.  I marked ones I thought shoudl be moved in blue and that is the list above.  
https://exbpbox.box.com/s/aj6t1c2tokoxs0g2a7in1yu7ioy136gk

**Comment by bundfussr** [comment]
I think classes and their methods should remain in one place, e.g., `format.smq_select()` should stay in `create_query_data.R` where the `smq_select` class is defined.

I would also keep functions which are just helper functions for one functions like `assert_terms()` in the place where the one function is defined.

**Comment by bundfussr** [comment]
`%notin%` may be useful in user scripts, i.e., maybe we should keep it in admiral.

**Comment by bms63** [comment]
should we keep `assert_db_requirements` in admiral or move here?

**Comment by thomas-neitmann** [comment]
> %notin% may be useful in user scripts, i.e., maybe we should keep it in admiral.

I'd rather not. While it could certainly be useful I'd rather like to keep {admiral} focussed on derivations and underlying data manipulation functions like `filter_extreme()`.

**Comment by thomas-neitmann** [comment]
> I think classes and their methods should remain in one place, e.g., `format.smq_select()` should stay in `create_query_data.R` where the `smq_select` class is defined.
> 
> I would also keep functions which are just helper functions for one functions like `assert_terms()` in the place where the one function is defined.

Agreed!

**Comment by bundfussr** [comment]
I would keep `assert_db_requirements()` in admiral because it is used in `get_terms_from_db()` and it is unlikely that it will be used by any other function.

**Comment by bms63** [comment]
@bundfussr @thomas-neitmann I have updated the list with where "developer-facing" functions should have their final resting place.  Any issues that you see or misgivings?

**Comment by bundfussr** [comment]
The list in the issue description looks fine to me.

**Comment by thomas-neitmann** [comment]
Look good to me 👍 

Thanks a lot for putting in the effort @bms63!
