### ISSUE TITLE
General Issue: Increase test coverage for `expect_dfs_equal`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#93]
### Background Information

We need to increase test coverage for our functions.  The below screenshot has the function and gap in test coverage that we need to write additional unit tests.  

![image](https://user-images.githubusercontent.com/10111024/191759254-0938f16d-8823-47cc-bd3b-0470649fa257.png)

### Definition of Done

New test written that covers the red gap area for this function.

**Comment by bms63** [comment]
@PoojaKumari05 same for this one

**Comment by PoojaKumari05** [comment]
> @PoojaKumari05 same for this one
@bms63 - yes will wrap this up by next week

**Comment by PoojaKumari05** [comment]
@bms63 This issue can be closed as the current test coverage is 100% for this.
![image](https://user-images.githubusercontent.com/90273880/220574953-5455c63b-ef67-4303-8f97-35c0d5e33721.png)
