### ISSUE TITLE
General Issue: Increase test coverage for `addin_format_testthat.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#99]
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests.

This one might be challenging and I'm not entirely sure it can be done.  

![image](https://user-images.githubusercontent.com/10111024/191840025-f40bf76e-b56f-42c1-9c56-7ff153d08fd5.png)

### Definition of Done

New test written that covers the red gap area for this function.

Use `devtools::test_coverage()` to reproduce the screenshot

**Comment by bms63** [comment]
Is this covered in your PR @bundfussr?   If not, do you think it is doable?

**Comment by bundfussr** [comment]
@bms63 this is not covered in my PR.

I am not sure if it is possible to unit test because the unit tests run outside of RStudio. Maybe there are packages available which simulate the RStudio environment? @thomas-neitmann , any ideas?
